//! Every dynamic variable, in display order: group, name, arguments, example, description, generator.
//! `mod.rs` skips formatting this file so each entry stays one readable row.

use super::data::*;
use super::generators as g;
use super::{DynamicVar, Generator};

const IDS: &str = "IDs";
const NUMBERS: &str = "Numbers";
const TEXT: &str = "Text";
const WORDS: &str = "Words";
const LOREM: &str = "Lorem ipsum";
const DATES: &str = "Dates & times";
const PEOPLE: &str = "People";
const INTERNET: &str = "Internet";
const LOCATION: &str = "Location";
const FINANCE: &str = "Finance";
const BUSINESS: &str = "Business";
const COMMERCE: &str = "Commerce";
const FILES: &str = "Files";
const DATABASES: &str = "Databases";
const IMAGES: &str = "Images";
const COLORS: &str = "Colors";

/// The groups in display order.
#[cfg(test)]
pub(super) const GROUPS: &[&str] = &[
    IDS, NUMBERS, TEXT, WORDS, LOREM, DATES, PEOPLE, INTERNET, LOCATION, FINANCE, BUSINESS, COMMERCE, FILES, DATABASES,
    IMAGES, COLORS,
];

const fn v(
    group: &'static str,
    name: &'static str,
    args: &'static str,
    example: &'static str,
    description: &'static str,
    generator: Generator,
) -> DynamicVar {
    DynamicVar { name, group, description, example, args, generator }
}

pub(super) static CATALOG: &[DynamicVar] = &[
    // IDs
    v(IDS, "$guid", "", "611c2e81-2ccb-42d8-9ddc-2d0bfa65c1b4", "A random UUID v4.", g::uuid_v4),
    v(IDS, "$uuid", "", "3f1c9b0e-7d2a-4c8e-9a51-2b6f0d4e8c17", "A random UUID v4.", g::uuid_v4),
    v(IDS, "$randomUUID", "", "6929bb52-3ab2-448a-9796-d6480ecad36b", "A random UUID v4.", g::uuid_v4),
    v(IDS, "$uuidv7", "", "01992f3a-8b4c-7d2e-9f10-3a5b7c9d1e2f",
      "A time-ordered UUID v7: IDs made later sort after earlier ones.", g::uuid_v7),
    v(IDS, "$ulid", "", "01K67Q3K7V5X2M9N4P6R8T0W1Y", "A ULID: 26 characters that sort by creation time.", g::ulid),
    v(IDS, "$nanoid", "(size)", "V1StGXR8_Z5jdHi6B-myT", "A URL-safe Nano ID, 21 characters unless you give a size.", g::nanoid),
    v(IDS, "$objectId", "", "66f7c2a4e1b3d59f0a2c4e81",
      "A MongoDB ObjectId: 24 hex characters that start with the creation time.", g::object_id),
    v(IDS, "$snowflake", "", "1972248110573953024",
      "A Twitter-style snowflake ID: a 64-bit number that grows with time.", g::snowflake),
    v(IDS, "$traceparent", "", "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01",
      "A W3C Trace Context traceparent header value with random trace and span IDs.", g::traceparent),
    v(IDS, "$randomHex", "(length)", "9f86d081884c7d659a2feaa0c55ad015",
      "Random lowercase hex, 32 characters unless you give a length.", g::random_hex),

    // Numbers
    v(NUMBERS, "$randomInt", "(min, max)", "802", "A random integer from 0 to 1000, or from min to max.", g::random_int),
    v(NUMBERS, "$randomFloat", "(min, max, decimals)", "531.27",
      "A random number from 0 to 1000 with 2 decimals, or in your range and precision.", g::random_float),
    v(NUMBERS, "$randomDigits", "(length)", "042917",
      "6 random digits (leading zeros kept) for codes and PINs, or as many as you ask for.", g::digits),
    v(NUMBERS, "$randomInt64", "", "-7239104857163029471",
      "A random signed 64-bit integer, usually beyond JavaScript's safe integer range.",
      |_| Some(rand::random::<i64>().to_string())),
    v(NUMBERS, "$randomBoolean", "", "true", "true or false.", |c| Some(c.pick(&["true", "false"]).into())),

    // Text
    v(TEXT, "$randomAlphaNumeric", "(length)", "y",
      "One random lowercase letter or digit, or as many as you ask for.", g::alphanumeric),
    v(TEXT, "$randomString", "(length)", "aZ3kQ9xLm2PvT8wR",
      "Random letters and digits, 16 characters unless you give a length.", g::string),
    v(TEXT, "$randomPassword", "(length)", "t9iXe7COoDKv8k3",
      "A random 15-character alphanumeric password, or the length you give.", g::password),
    v(TEXT, "$randomStrongPassword", "(length)", "q7#Rt2!mZx9@Lp4&",
      "A 16-character password (or 4 and more you choose) with upper and lower case letters, digits and symbols.",
      g::strong_password),
    v(TEXT, "$randomBase64", "(bytes)", "q83vEjRWeJq8z0Ed0ZrM3A==",
      "Base64 of 16 random bytes, or of as many bytes as you ask for.", g::random_base64),
    v(TEXT, "$randomUnicodeString", "(length)", "éñ東京שלום😀Жω한مर🎉ß",
      "16 characters (or your length) mixing accents, Greek, Cyrillic, CJK, right-to-left scripts and emoji.",
      g::unicode_string),
    v(TEXT, "$randomEmoji", "", "🚀",
      "A random emoji; some are several code points (skin tones, flags, joined sequences).", |c| c.one(EMOJI)),
    v(TEXT, "$randomFrom", "(values…)", "green", "One of the values you list, e.g. $randomFrom(red, green, blue).",
      g::random_from),
    v(TEXT, "$randomSlug", "(words)", "distributed-token-cache",
      "A URL slug of 3 random words, or of as many words as you ask for.", g::slug),
    v(TEXT, "$randomAbbreviation", "", "JSON", "A random tech abbreviation.", |c| c.one(ABBREVIATIONS)),

    // Words
    v(WORDS, "$randomNoun", "", "bandwidth", "A random noun.", |c| c.one(NOUNS)),
    v(WORDS, "$randomVerb", "", "parse", "A random verb.", |c| c.one(VERBS)),
    v(WORDS, "$randomIngverb", "", "navigating", "A random verb ending in -ing.", |c| c.one(ING_VERBS)),
    v(WORDS, "$randomAdjective", "", "multi-byte", "A random adjective.", |c| c.one(ADJECTIVES)),
    v(WORDS, "$randomWord", "", "matrix", "A random word.", g::word),
    v(WORDS, "$randomWords", "(count)", "synergies token bandwidth",
      "2 to 5 random words, or as many as you ask for.", g::words),
    v(WORDS, "$randomPhrase", "", "You can't parse the monitor without navigating the neural SQL feed!",
      "A random tech phrase.", g::phrase),

    // Lorem ipsum
    v(LOREM, "$randomLoremWord", "", "est", "A word of lorem ipsum.", g::lorem_word),
    v(LOREM, "$randomLoremWords", "(count)", "vel repellat nobis",
      "3 words of lorem ipsum, or as many as you ask for.", g::lorem_words_var),
    v(LOREM, "$randomLoremSentence", "(words)", "Molestias consequuntur nisi non quod.",
      "A sentence of lorem ipsum, 3 to 10 words unless you give a number.", g::lorem_sentence_var),
    v(LOREM, "$randomLoremSentences", "(count)", "Et sint voluptas similique iure. Amet perspiciatis quia rem.",
      "2 to 6 sentences of lorem ipsum, or as many as you ask for.", g::lorem_sentences_var),
    v(LOREM, "$randomLoremParagraph", "(sentences)",
      "Ab aliquid odio iste quo voluptas. Voluptatem quia natus est. Minus rerum ut eos dolorem.",
      "A paragraph of 3 to 6 lorem ipsum sentences, or as many sentences as you ask for.", g::lorem_paragraph),
    v(LOREM, "$randomLoremParagraphs", "(count)",
      "Voluptatem rem magnam aliquam ab id. Aut quaerat qui.\nNemo quia et. Odio ut ea est.\nQuo sint vel. Nisi velit id.",
      "3 paragraphs of lorem ipsum on separate lines, or as many as you ask for.", g::lorem_paragraphs),
    v(LOREM, "$randomLoremText", "", "Quisquam asperiores exercitationem ut ipsum. Aut eius molestias.",
      "A random amount of lorem ipsum text.", g::lorem_text),
    v(LOREM, "$randomLoremSlug", "(words)", "eos-aperiam-accusamus",
      "A URL slug of 3 lorem ipsum words, or of as many words as you ask for.", g::lorem_slug),
    v(LOREM, "$randomLoremLines", "(count)", "Ducimus in ut mollitia.\nA itaque non.",
      "1 to 5 lines of lorem ipsum, or as many as you ask for.", g::lorem_lines),

    // Dates & times
    v(DATES, "$timestamp", "(offset)", "1790588467",
      "The current Unix time in seconds; an offset such as +1h or -7d moves it.", g::timestamp),
    v(DATES, "$timestampMs", "(offset)", "1790588467123",
      "The current Unix time in milliseconds; an offset such as +1h or -7d moves it.", g::timestamp_ms),
    v(DATES, "$isoTimestamp", "(offset)", "2026-09-28T09:41:07.123Z",
      "The current time in ISO 8601 (UTC, milliseconds); an offset such as -7d moves it.", g::iso_timestamp),
    v(DATES, "$isoDate", "(offset)", "2026-09-28",
      "Today's date in UTC as YYYY-MM-DD; an offset such as +30d moves it.", g::date_at),
    v(DATES, "$today", "", "2026-09-28", "Today's date in UTC as YYYY-MM-DD.", |c| g::days_from_today(c, 0)),
    v(DATES, "$tomorrow", "", "2026-09-29", "Tomorrow's date in UTC as YYYY-MM-DD.", |c| g::days_from_today(c, 1)),
    v(DATES, "$yesterday", "", "2026-09-27", "Yesterday's date in UTC as YYYY-MM-DD.", |c| g::days_from_today(c, -1)),
    v(DATES, "$httpDate", "(offset)", "Mon, 28 Sep 2026 09:41:07 GMT",
      "The current time as an HTTP date, for headers such as If-Modified-Since; takes an offset.", g::http_date),
    v(DATES, "$randomDateTime", "(from, to)", "2026-03-14T16:22:05.481Z",
      "A random ISO 8601 time within a year of now, or between two offsets such as (-30d, now).", g::date_time),
    v(DATES, "$randomDate", "(from, to)", "2026-11-03",
      "A random date (YYYY-MM-DD) within a year of now, or between two offsets such as (now, +90d).", g::random_date),
    v(DATES, "$randomTime", "", "14:23:05", "A random time of day, HH:MM:SS.", g::random_time),
    v(DATES, "$randomDatePast", "(days)", "Mon Mar 02 2026 09:09:26 GMT+0000",
      "A random moment in the past year (or past days you give), in JavaScript date format.", g::date_past),
    v(DATES, "$randomDateFuture", "(days)", "Wed Mar 17 2027 13:11:50 GMT+0000",
      "A random moment in the next year (or next days you give), in JavaScript date format.", g::date_future),
    v(DATES, "$randomDateRecent", "(days)", "Sun Sep 27 2026 23:12:37 GMT+0000",
      "A random moment in the last day (or last days you give), in JavaScript date format.", g::date_recent),
    v(DATES, "$randomWeekday", "", "Thursday", "A random day of the week.", |c| c.one(WEEKDAYS)),
    v(DATES, "$randomMonth", "", "February", "A random month.", |c| c.one(MONTHS)),
    v(DATES, "$randomTimezone", "", "Asia/Kolkata", "A random IANA time zone.", |c| c.one(TIMEZONES)),

    // People
    v(PEOPLE, "$randomFirstName", "", "Ethan", "A random first name.", |c| c.one(FIRST_NAMES)),
    v(PEOPLE, "$randomLastName", "", "Schneider", "A random last name.", |c| c.one(LAST_NAMES)),
    v(PEOPLE, "$randomFullName", "", "Priya Fernández", "A random first and last name.", g::full_name),
    v(PEOPLE, "$randomNamePrefix", "", "Dr.", "A random name prefix.", |c| c.one(NAME_PREFIXES)),
    v(PEOPLE, "$randomNameSuffix", "", "MD", "A random name suffix.", |c| c.one(NAME_SUFFIXES)),
    v(PEOPLE, "$randomGender", "", "female", "female, male or non-binary.", |c| c.one(GENDERS)),
    v(PEOPLE, "$randomBirthdate", "(minAge, maxAge)", "1987-04-12",
      "A date of birth (YYYY-MM-DD) of someone aged 18 to 80, or in your age range.", g::birthdate),
    v(PEOPLE, "$randomAge", "(min, max)", "34", "A random age from 18 to 80, or in your range.", g::age),
    v(PEOPLE, "$randomPhoneNumber", "", "704-261-3424", "A ten-digit phone number.",
      |c| Some(c.pattern("N##-N##-####"))),
    v(PEOPLE, "$randomPhoneNumberExt", "", "27-299-983-3864", "A phone number with a two-digit extension.",
      |c| Some(c.pattern("MM-N##-N##-####"))),
    v(PEOPLE, "$randomE164Phone", "(country)", "+14155552671",
      "A mobile number in E.164 format from a random country, or from a country code such as DE.", g::e164_phone),
    v(PEOPLE, "$randomJobArea", "", "Mobility", "A random job area.", |c| c.one(JOB_AREAS)),
    v(PEOPLE, "$randomJobDescriptor", "", "Senior", "A random job descriptor.", |c| c.one(JOB_DESCRIPTORS)),
    v(PEOPLE, "$randomJobTitle", "", "International Creative Liaison", "A random job title.", g::job_title),
    v(PEOPLE, "$randomJobType", "", "Coordinator", "A random job type.", |c| c.one(JOB_TYPES)),

    // Internet
    v(INTERNET, "$randomEmail", "", "pablo.garcia62@example.com",
      "A random email address at a reserved example domain, so no real inbox gets mail.", g::email),
    v(INTERNET, "$randomExampleEmail", "", "Talon.Weber28@example.net",
      "A random email address at example.com, example.net or example.org.", g::example_email),
    v(INTERNET, "$randomUserName", "", "Lottie.Smith24", "A random username.", g::user_name),
    v(INTERNET, "$randomDomainName", "", "hoffmann.io", "A random domain name.", g::domain_name),
    v(INTERNET, "$randomDomainSuffix", "", "org", "A random top-level domain.", |c| c.one(DOMAIN_SUFFIXES)),
    v(INTERNET, "$randomDomainWord", "", "meyer", "A random domain name without the suffix.", g::domain_word),
    v(INTERNET, "$randomUrl", "", "https://schmidt.net", "A random URL.", g::url),
    v(INTERNET, "$randomIP", "", "241.102.234.100", "A random IPv4 address.", g::ipv4),
    v(INTERNET, "$randomIPV6", "", "dbe2:7ae6:119b:c161:1560:6dda:3a9b:90a9", "A random IPv6 address.", g::ipv6),
    v(INTERNET, "$randomPrivateIP", "", "192.168.14.203",
      "A private IPv4 address (10.0.0.0/8, 172.16.0.0/12 or 192.168.0.0/16).", g::private_ipv4),
    v(INTERNET, "$randomMACAddress", "", "32:d4:68:5f:b4:c7", "A random MAC address.", g::mac),
    v(INTERNET, "$randomPort", "", "51837", "A random non-privileged port, 1024 to 65535.",
      |c| Some(c.between(1024, 65_535).to_string())),
    v(INTERNET, "$randomProtocol", "", "https", "http or https.", |c| c.one(&["http", "https"])),
    v(INTERNET, "$randomHttpMethod", "", "PATCH", "A random HTTP method.", |c| c.one(HTTP_METHODS)),
    v(INTERNET, "$randomHttpStatus", "", "404", "A common HTTP status code.",
      |c| Some(c.pick(HTTP_STATUSES).to_string())),
    v(INTERNET, "$randomUserAgent", "",
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36",
      "A current browser user agent (Chrome, Edge, Firefox, Safari; desktop and mobile).", |c| c.one(USER_AGENTS)),
    v(INTERNET, "$randomSemver", "", "7.0.5", "A random semantic version number.", g::semver),

    // Location
    v(LOCATION, "$randomCountry", "", "Kazakhstan", "A random country.", |c| Some(c.pick(COUNTRIES).2.into())),
    v(LOCATION, "$randomCountryCode", "", "CV", "A two-letter country code (ISO 3166-1 alpha-2).",
      |c| Some(c.pick(COUNTRIES).0.into())),
    v(LOCATION, "$randomCountryCodeAlpha3", "", "CPV", "A three-letter country code (ISO 3166-1 alpha-3).",
      |c| Some(c.pick(COUNTRIES).1.into())),
    v(LOCATION, "$randomCity", "", "Lisbon", "A random city.", |c| c.one(CITIES)),
    v(LOCATION, "$randomStreetName", "", "Maple Avenue", "A random street name.", g::street_name),
    v(LOCATION, "$randomStreetAddress", "", "5742 Maple Avenue", "A random street address.", g::street_address),
    v(LOCATION, "$randomState", "", "California", "A random US state.", |c| Some(c.pick(US_STATES).0.into())),
    v(LOCATION, "$randomStateAbbr", "", "CA", "A random US state code.", |c| Some(c.pick(US_STATES).1.into())),
    v(LOCATION, "$randomPostalCode", "", "94107",
      "A five-digit postal code, the format used in the US, Germany, France, Spain, Italy and more.",
      |c| Some(c.pattern("#####"))),
    v(LOCATION, "$randomLatitude", "(min, max)", "55.2099", "A random latitude, or one between min and max.",
      g::latitude),
    v(LOCATION, "$randomLongitude", "(min, max)", "-159.9757", "A random longitude, or one between min and max.",
      g::longitude),
    v(LOCATION, "$randomCoordinates", "", "52.5200,13.4050", "A random latitude,longitude pair.", g::coordinates),
    v(LOCATION, "$randomLocale", "", "sr", "A two-letter language code (ISO 639-1).", |c| c.one(LANGUAGE_CODES)),
    v(LOCATION, "$randomLanguageCode", "", "de", "A two-letter language code (ISO 639-1).",
      |c| c.one(LANGUAGE_CODES)),
    v(LOCATION, "$randomLanguageTag", "", "pt-BR", "A BCP 47 language tag, as sent in Accept-Language.",
      |c| c.one(LANGUAGE_TAGS)),

    // Finance
    v(FINANCE, "$randomBankAccount", "", "09454073", "A random 8-digit bank account number.",
      |c| Some(c.pattern("########"))),
    v(FINANCE, "$randomBankAccountName", "", "Home Loan Account", "A random bank account name.",
      |c| Some(format!("{} Account", c.pick(BANK_ACCOUNT_TYPES)))),
    v(FINANCE, "$randomBankAccountIban", "(country)", "DE89370400440532013000",
      "An IBAN with valid check digits from AT, BE, CH, DE, DK, ES, FR, GB, IE, NL or SE, or the country you give.",
      g::iban),
    v(FINANCE, "$randomBankAccountBic", "", "EZIAUGJ1", "A random BIC (SWIFT code).", g::bic),
    v(FINANCE, "$randomCreditCardMask", "", "3622", "The last four digits of a card number.",
      |c| Some(c.pattern("####"))),
    v(FINANCE, "$randomCreditCardNumber", "(brand)", "4111111111111111",
      "A card number that passes the Luhn check, on well-known test prefixes; brand: visa, mastercard, amex, discover, jcb or diners.",
      g::card_number),
    v(FINANCE, "$randomCreditCardCvv", "", "839", "A random three-digit card security code.", |c| Some(c.pattern("###"))),
    v(FINANCE, "$randomCreditCardExpiry", "", "08/29", "A card expiry date in the next five years, MM/YY.",
      g::card_expiry),
    v(FINANCE, "$randomTransactionType", "", "payment", "A random transaction type.", |c| c.one(TRANSACTION_TYPES)),
    v(FINANCE, "$randomCurrencyCode", "", "EUR", "A three-letter currency code (ISO 4217).",
      |c| Some(c.pick(CURRENCIES).0.into())),
    v(FINANCE, "$randomCurrencyName", "", "Pound Sterling", "A random currency name.",
      |c| Some(c.pick(CURRENCIES).1.into())),
    v(FINANCE, "$randomCurrencySymbol", "", "£", "A random currency symbol.", |c| Some(c.pick(CURRENCIES).2.into())),
    v(FINANCE, "$randomBitcoin", "", "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
      "A Bitcoin address with a valid checksum.", g::bitcoin),

    // Business
    v(BUSINESS, "$randomCompanyName", "", "Weber GmbH", "A random company name.", g::company_name),
    v(BUSINESS, "$randomCompanySuffix", "", "LLC", "A random company suffix.", |c| c.one(COMPANY_SUFFIXES)),
    v(BUSINESS, "$randomBs", "", "harness frictionless platforms", "A random phrase of business-speak.", g::bs),
    v(BUSINESS, "$randomBsAdjective", "", "frictionless", "A random business-speak adjective.",
      |c| c.one(BS_ADJECTIVES)),
    v(BUSINESS, "$randomBsBuzz", "", "repurpose", "A random business-speak buzzword.", |c| c.one(BS_BUZZ)),
    v(BUSINESS, "$randomBsNoun", "", "e-services", "A random business-speak noun.", |c| c.one(BS_NOUNS)),
    v(BUSINESS, "$randomCatchPhrase", "", "Future-proofed heuristic open architecture", "A random catchphrase.",
      g::catch_phrase),
    v(BUSINESS, "$randomCatchPhraseAdjective", "", "Self-enabling", "A random catchphrase adjective.",
      |c| c.one(CATCH_ADJECTIVES)),
    v(BUSINESS, "$randomCatchPhraseDescriptor", "", "bandwidth-monitored", "A random catchphrase descriptor.",
      |c| c.one(CATCH_DESCRIPTORS)),
    v(BUSINESS, "$randomCatchPhraseNoun", "", "secured line", "A random catchphrase noun.", |c| c.one(CATCH_NOUNS)),

    // Commerce
    v(COMMERCE, "$randomPrice", "(min, max)", "531.55", "A price from 0.00 to 1000.00, or between min and max.",
      g::price),
    v(COMMERCE, "$randomProduct", "", "Towels", "A random product.", |c| c.one(PRODUCTS)),
    v(COMMERCE, "$randomProductAdjective", "", "Incredible", "A random product adjective.",
      |c| c.one(PRODUCT_ADJECTIVES)),
    v(COMMERCE, "$randomProductMaterial", "", "Bamboo", "A random product material.", |c| c.one(PRODUCT_MATERIALS)),
    v(COMMERCE, "$randomProductName", "", "Handmade Concrete Chair", "A random product name.", g::product_name),
    v(COMMERCE, "$randomDepartment", "", "Electronics", "A random store department.", |c| c.one(DEPARTMENTS)),
    v(COMMERCE, "$randomIsbn10", "", "0306406152", "An ISBN-10 with a valid check digit.", g::isbn10),
    v(COMMERCE, "$randomIsbn13", "", "9780306406157", "An ISBN-13 with a valid check digit.", g::isbn13),
    v(COMMERCE, "$randomEan13", "", "4006381333931", "An EAN-13 barcode number with a valid check digit.", g::ean13),
    v(COMMERCE, "$randomUpc", "", "036000291452", "A UPC-A barcode number with a valid check digit.", g::upc),

    // Files
    v(FILES, "$randomFileName", "", "heuristic_socket.gltf", "A random file name, extensions of all kinds.",
      |c| g::file_name(c, false)),
    v(FILES, "$randomFileType", "", "model", "A random file type (the first part of a MIME type).",
      |c| g::file_type(c, false)),
    v(FILES, "$randomFileExt", "", "woff2", "A random file extension.", |c| g::file_ext(c, false)),
    v(FILES, "$randomCommonFileName", "", "well_modulated_driver.mp4", "A random file name with a common extension.",
      |c| g::file_name(c, true)),
    v(FILES, "$randomCommonFileType", "", "image", "A common file type (the first part of a MIME type).",
      |c| g::file_type(c, true)),
    v(FILES, "$randomCommonFileExt", "", "png", "A common file extension.", |c| g::file_ext(c, true)),
    v(FILES, "$randomFilePath", "", "/var/log/modular_payload.json", "A random absolute file path.", g::file_path),
    v(FILES, "$randomDirectoryPath", "", "/usr/local/bin", "A random directory path.", |c| c.one(DIRECTORIES)),
    v(FILES, "$randomMimeType", "", "application/json", "A random MIME type.", g::mime_type),

    // Databases
    v(DATABASES, "$randomDatabaseColumn", "", "updatedAt", "A random database column name.", |c| c.one(DB_COLUMNS)),
    v(DATABASES, "$randomDatabaseType", "", "varchar", "A random database column type.", |c| c.one(DB_TYPES)),
    v(DATABASES, "$randomDatabaseCollation", "", "utf8mb4_unicode_ci", "A random database collation.",
      |c| c.one(DB_COLLATIONS)),
    v(DATABASES, "$randomDatabaseEngine", "", "InnoDB", "A random database engine.", |c| c.one(DB_ENGINES)),

    // Images
    v(IMAGES, "$randomAvatarImage", "", "https://avatars.githubusercontent.com/u/30218384",
      "The URL of a random avatar image.", |c| Some(format!("https://avatars.githubusercontent.com/u/{}", c.between(1, 99_999_999)))),
    v(IMAGES, "$randomImageUrl", "(width, height)", "https://picsum.photos/seed/k3v9x2qa/640/480",
      "The URL of a random 640×480 image, or of the size you give.", g::image_url),
    v(IMAGES, "$randomAbstractImage", "(width, height)", "https://loremflickr.com/640/480/abstract?lock=4821",
      "The URL of a random abstract image.", |c| g::category_image(c, "abstract")),
    v(IMAGES, "$randomAnimalsImage", "(width, height)", "https://loremflickr.com/640/480/animals?lock=77",
      "The URL of a random animal image.", |c| g::category_image(c, "animals")),
    v(IMAGES, "$randomBusinessImage", "(width, height)", "https://loremflickr.com/640/480/business?lock=3190",
      "The URL of a random business image.", |c| g::category_image(c, "business")),
    v(IMAGES, "$randomCatsImage", "(width, height)", "https://loremflickr.com/640/480/cats?lock=15023",
      "The URL of a random cat image.", |c| g::category_image(c, "cats")),
    v(IMAGES, "$randomCityImage", "(width, height)", "https://loremflickr.com/640/480/city?lock=908",
      "The URL of a random city image.", |c| g::category_image(c, "city")),
    v(IMAGES, "$randomFoodImage", "(width, height)", "https://loremflickr.com/640/480/food?lock=6412",
      "The URL of a random food image.", |c| g::category_image(c, "food")),
    v(IMAGES, "$randomNightlifeImage", "(width, height)", "https://loremflickr.com/640/480/nightlife?lock=221",
      "The URL of a random nightlife image.", |c| g::category_image(c, "nightlife")),
    v(IMAGES, "$randomFashionImage", "(width, height)", "https://loremflickr.com/640/480/fashion?lock=5566",
      "The URL of a random fashion image.", |c| g::category_image(c, "fashion")),
    v(IMAGES, "$randomPeopleImage", "(width, height)", "https://loremflickr.com/640/480/people?lock=42",
      "The URL of a random image of people.", |c| g::category_image(c, "people")),
    v(IMAGES, "$randomNatureImage", "(width, height)", "https://loremflickr.com/640/480/nature?lock=8080",
      "The URL of a random nature image.", |c| g::category_image(c, "nature")),
    v(IMAGES, "$randomSportsImage", "(width, height)", "https://loremflickr.com/640/480/sports?lock=1234",
      "The URL of a random sports image.", |c| g::category_image(c, "sports")),
    v(IMAGES, "$randomTransportImage", "(width, height)", "https://loremflickr.com/640/480/transport?lock=97",
      "The URL of a random transport image.", |c| g::category_image(c, "transport")),
    v(IMAGES, "$randomImageDataUri", "(width, height)",
      "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22640%22%20height%3D%22480%22%3E%3C%2Fsvg%3E",
      "A random single-color SVG image as a data URI.", g::image_data_uri),

    // Colors
    v(COLORS, "$randomColor", "", "fuchsia", "A random color name.", |c| c.one(COLOR_NAMES)),
    v(COLORS, "$randomHexColor", "", "#47594a", "A random hex color.", g::hex_color),
    v(COLORS, "$randomRgbColor", "", "rgb(71, 89, 74)", "A random CSS rgb() color.", g::rgb_color),
    v(COLORS, "$randomHslColor", "", "hsl(210, 45%, 38%)", "A random CSS hsl() color.", g::hsl_color),
];
