// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabView } from "./LabView";
import type { ProgressView } from "./ProgressView";
import type { Rewards } from "./Rewards";

/**
 * Pushed as the `academy` event: the lab, progress, and what was just earned.
 */
export type AcademyUpdate = { lab: LabView | null, progress: ProgressView, rewards: Rewards | null, };
