// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snapshot } from "./Snapshot";
import type { TimePoint } from "./TimePoint";

/**
 * The run in progress (the UI restores its view with it).
 */
export type ActiveLoadRun = { runId: string, testId: string, workspacePath: string, name: string, 
/**
 * Unix epoch milliseconds.
 */
startedAt: number, plannedMs: number, 
/**
 * The latest snapshot (its `points` empty) and every chart point so far,
 * so a reloaded window shows the whole run.
 */
snapshot: Snapshot | null, points: Array<TimePoint>, };
