// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether edits by AI agents need the user's approval.
 */
export type AgentChanges = "allow" | "ask";
