// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentChanges } from "./AgentChanges";
import type { AgentTraffic } from "./AgentTraffic";

/**
 * AI agents controlling the app over MCP (docs/architecture.md, "AI agents").
 */
export type AgentSettings = { 
/**
 * Off: the first tool call asks the user to turn it on.
 */
enabled: boolean, changes: AgentChanges, traffic: AgentTraffic, 
/**
 * Open what an agent works on (tabs, responses, runs).
 */
follow: boolean, 
/**
 * Run agent tools without the app when it is closed (nothing can be approved then).
 */
headless: boolean, };
