// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfirmKind } from "./ConfirmKind";

/**
 * An agent's action waiting for the user's answer.
 */
export type AgentConfirm = { id: string, sessionId: string, client: string, kind: ConfirmKind, title: string, message: string, 
/**
 * What exactly (requests, hosts, the load plan…), one line each.
 */
items: Array<string>, confirmLabel: string, 
/**
 * "Allow for this session" is offered.
 */
sessionOption: boolean, danger: boolean, 
/**
 * Unix epoch milliseconds; unanswered by then = refused.
 */
expiresAt: number, };
