// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityStatus } from "./ActivityStatus";
import type { AgentTarget } from "./AgentTarget";

/**
 * One tool call in the activity log (updated in place while it runs).
 */
export type AgentActivity = { id: string, sessionId: string, client: string, tool: string, 
/**
 * What the agent asked for, in words ("Send GET {{baseUrl}}/users").
 */
title: string, status: ActivityStatus, 
/**
 * The outcome in a few words, or why it failed.
 */
detail: string | null, 
/**
 * Unix epoch milliseconds.
 */
startedAt: number, durationMs: number | null, target: AgentTarget | null, };
