// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something in the app an agent action is about (clicking the entry opens it).
 */
export type AgentTarget = { "type": "request", path: string, } | { "type": "folder", path: string, } | { "type": "loadTest", id: string, } | { "type": "server", id: string, } | { "type": "runner", folder: string, name: string, } | { "type": "environments" };
