// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentActivity } from "./AgentActivity";
import type { AgentConfirm } from "./AgentConfirm";
import type { AgentSession } from "./AgentSession";

/**
 * Everything the Agents panel shows (after a window reload).
 */
export type AgentState = { sessions: Array<AgentSession>, 
/**
 * Oldest first.
 */
activity: Array<AgentActivity>, pending: Array<AgentConfirm>, };
