// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An agent connected over MCP.
 */
export type AgentSession = { id: string, 
/**
 * Display name, e.g. "Claude Code".
 */
client: string, 
/**
 * Unix epoch milliseconds.
 */
connectedAt: number, };
