// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";

export type ApiError = { 
/**
 * Machine-readable code (`notFound`, `network`, `invalidInput`, ...).
 */
code: string, message: string, 
/**
 * Network failure category when `code` is `network`.
 */
networkKind: ErrorKind | null, };
