// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Zoom and fonts of the app window (Settings → General).
 */
export type Appearance = { 
/**
 * Page zoom in percent (⌘+ / ⌘− / ⌘0).
 */
zoom: number, 
/**
 * Font of the interface; empty = the system font.
 */
uiFont: string, 
/**
 * Font of editors, responses and other code; empty = the system's monospace font.
 */
codeFont: string, 
/**
 * Text size in editors and response bodies, in CSS pixels (before zoom).
 */
codeFontSize: number, 
/**
 * Show programming ligatures (`=>` as one glyph) when the code font has them.
 */
ligatures: boolean, };
