// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicVarInfo } from "./DynamicVarInfo";

export type AppInfo = { version: string, 
/**
 * CI build number and commit, when built by CI.
 */
build: string | null, dataDir: string, platform: string, dynamicVariables: Array<string>, 
/**
 * Every dynamic variable with its description and an example (autocomplete, hints).
 */
dynamicCatalog: Array<DynamicVarInfo>, 
/**
 * The `zorvik` command-line tool installed with the app (AI agents run `zorvik mcp`).
 */
cliPath: string | null, 
/**
 * Typing `zorvik` in a terminal runs it.
 */
cliOnPath: boolean, };
