// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JwtAlgorithm } from "./JwtAlgorithm";

/**
 * Atlassian ASAP (service-to-service JWT).
 */
export type AsapConfig = { issuer: string, subject?: string, 
/**
 * One or more audiences, comma-separated.
 */
audience: string, 
/**
 * The key id (`kid`) the receiver looks the public key up by.
 */
keyId: string, 
/**
 * PEM private key.
 */
privateKey: string, algorithm: JwtAlgorithm, 
/**
 * Lifetime of each token, in seconds (at most 3600).
 */
expiresIn: number, 
/**
 * Extra claims, as JSON.
 */
claims?: string, };
