// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKeyLocation } from "./ApiKeyLocation";
import type { OAuth2Config } from "./OAuth2Config";

export type Auth = { "type": "inherit" } | { "type": "none" } | { "type": "basic", username: string, password: string, } | { "type": "bearer", token: string, prefix: string, } | { "type": "apiKey", key: string, value: string, location: ApiKeyLocation, } | { "type": "oauth2" } & OAuth2Config;
