// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKeyLocation } from "./ApiKeyLocation";
import type { AsapConfig } from "./AsapConfig";
import type { AwsSigV4Config } from "./AwsSigV4Config";
import type { EdgeGridConfig } from "./EdgeGridConfig";
import type { HawkConfig } from "./HawkConfig";
import type { JwtConfig } from "./JwtConfig";
import type { OAuth1Config } from "./OAuth1Config";
import type { OAuth2Config } from "./OAuth2Config";

export type Auth = { "type": "inherit" } | { "type": "none" } | { "type": "basic", username: string, password: string, } | { "type": "bearer", token: string, prefix: string, } | { "type": "apiKey", key: string, value: string, location: ApiKeyLocation, } | { "type": "oauth2" } & OAuth2Config | { "type": "digest", username: string, password: string, } | { "type": "ntlm", 
/**
 * `user`, `DOMAIN\user` or `user@domain`.
 */
username: string, password: string, domain?: string, workstation?: string, } | { "type": "awsSigV4" } & AwsSigV4Config | { "type": "oauth1" } & OAuth1Config | { "type": "jwt" } & JwtConfig | { "type": "hawk" } & HawkConfig | { "type": "akamaiEdgeGrid" } & EdgeGridConfig | { "type": "asap" } & AsapConfig;
