// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunningServerInfo } from "./RunningServerInfo";

export type AutoStartResult = { started: Array<RunningServerInfo>, 
/**
 * "Name: reason" for servers that could not start.
 */
errors: Array<string>, };
