// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKeyLocation } from "./ApiKeyLocation";

/**
 * AWS Signature Version 4.
 */
export type AwsSigV4Config = { accessKey: string, secretKey: string, 
/**
 * Temporary credentials (STS): sent as `X-Amz-Security-Token`.
 */
sessionToken?: string, 
/**
 * e.g. `us-east-1`.
 */
region: string, 
/**
 * e.g. `execute-api`, `s3`, `sts`.
 */
service: string, 
/**
 * Sign in headers, or in the query string (a presigned URL).
 */
location?: ApiKeyLocation, };
