// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BodyType } from "./BodyType";
import type { GraphqlBody } from "./GraphqlBody";
import type { KeyValue } from "./KeyValue";
import type { MultipartField } from "./MultipartField";

/**
 * Request body. Data for every body type is kept, so switching the type in
 * the UI never loses what was typed; only `type` decides what is sent.
 */
export type Body = { type: BodyType, 
/**
 * JSON / text / XML body (also the message draft for WebSocket requests).
 */
text?: string, 
/**
 * Content-Type for `text` bodies (default text/plain).
 */
contentType?: string, form?: Array<KeyValue>, multipart?: Array<MultipartField>, 
/**
 * File path for binary bodies (absolute, or relative to the workspace root).
 */
file?: string, graphql?: GraphqlBody, };
