// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CertificateInfo = { subject: string, issuer: string, notBefore: string, notAfter: string, subjectAltNames: Array<string>, serial: string, };
