// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsoleLevel } from "./ConsoleLevel";

export type ConsoleEntry = { level: ConsoleLevel, message: string, };
