// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cookie as shown in the UI (response Cookies tab and the cookie manager).
 */
export type CookieInfo = { name: string, value: string, domain: string, path: string, 
/**
 * RFC 3339 expiry, `None` for session cookies.
 */
expires: string | null, secure: boolean, httpOnly: boolean, sameSite: string | null, };
