// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BadgeView } from "./BadgeView";
import type { UnitView } from "./UnitView";

export type CourseView = { units: Array<UnitView>, 
/**
 * Badges earned by how the learner works (unit badges are on the units).
 */
extraBadges: Array<BadgeView>, };
