// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shell a generated cURL command is meant for.
 */
export type CurlFlavor = "bash" | "cmd" | "powerShell";
