// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The start of a data file, for the runner's settings (`runner.preview`).
 */
export type DataPreview = { 
/**
 * `csv` or `json`.
 */
format: string, columns: Array<string>, 
/**
 * The first rows, values as variables see them, in column order.
 */
rows: Array<Array<string>>, 
/**
 * All rows.
 */
count: number, };
