// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Header flags of the response.
 */
export type DnsFlags = { 
/**
 * Authoritative answer.
 */
aa: boolean, 
/**
 * Truncated.
 */
tc: boolean, 
/**
 * Recursion desired.
 */
rd: boolean, 
/**
 * Recursion available.
 */
ra: boolean, 
/**
 * Authentic data (DNSSEC validated by the resolver).
 */
ad: boolean, 
/**
 * Checking disabled.
 */
cd: boolean, };
