// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options of DNS requests.
 */
export type DnsOptions = { 
/**
 * Resolver to ask. Empty: the system's. Otherwise `1.1.1.1`, `8.8.8.8:53`,
 * `tcp://1.1.1.1`, `tls://1.1.1.1` (DNS over TLS) or `https://…/dns-query` (DNS over HTTPS).
 */
server?: string, 
/**
 * Ask the server to resolve recursively (RD flag).
 */
recursion?: boolean, };
