// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DnsFlags } from "./DnsFlags";
import type { DnsQuestion } from "./DnsQuestion";
import type { DnsResultRecord } from "./DnsResultRecord";
import type { TlsInfo } from "./TlsInfo";

/**
 * The answer plus the variables that were referenced but not defined.
 */
export type DnsQueryResult = { unresolved: Array<string>, question: DnsQuestion, answers: Array<DnsResultRecord>, authority: Array<DnsResultRecord>, additional: Array<DnsResultRecord>, 
/**
 * NOERROR, NXDOMAIN, SERVFAIL, REFUSED, …
 */
rcode: string, rcodeValue: number, flags: DnsFlags, 
/**
 * Server that answered: `1.1.1.1:53`, or the DoH URL.
 */
server: string, 
/**
 * UDP, TCP, DoT, DoH, or `System` (the operating system's lookup, without DNS details).
 */
protocol: string, 
/**
 * Asked the DNS servers from this computer's network settings.
 */
system: boolean, 
/**
 * DNS over TLS/HTTPS: the negotiated TLS session.
 */
tls: TlsInfo | null, durationMs: number, 
/**
 * Size of the DNS response message in bytes.
 */
size: number, 
/**
 * Things worth knowing, e.g. "retried over TCP".
 */
notes: Array<string>, };
