// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One resource record, with its data as in a zone file (`10 mail.example.com.` for MX).
 */
export type DnsResultRecord = { name: string, type: string, class: string, ttl: number, data: string, };
