// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DnsRecord = { 
/**
 * Name, e.g. `api.example.test` or `*.example.test`.
 */
name: string, 
/**
 * A, AAAA, CNAME, TXT, MX, NS, PTR, SRV, CAA.
 */
type: string, 
/**
 * Record data as in a zone file (`10 mail.example.test` for MX).
 */
value: string, ttl: number, enabled?: boolean, };
