// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DnsRecord } from "./DnsRecord";

export type DnsServerConfig = { records?: Array<DnsRecord>, 
/**
 * Where names without a record go: empty = answer "no such name",
 * `system` = this computer's resolver, or a server such as `1.1.1.1`.
 */
upstream?: string, };
