// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A catalog entry for the UI (autocomplete and docs).
 */
export type DynamicVarInfo = { name: string, group: string, description: string, example: string, args: string, };
