// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Akamai EdgeGrid (EG1-HMAC-SHA256).
 */
export type EdgeGridConfig = { clientToken: string, clientSecret: string, accessToken: string, 
/**
 * Header names to sign, comma-separated (usually none).
 */
headersToSign?: string, 
/**
 * How much of a POST body is hashed, in bytes.
 */
maxBody: number, };
