// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Environment } from "./Environment";

export type EnvironmentEntry = { 
/**
 * File stem, used as the environment id.
 */
id: string, environment: Environment, };
