// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Variable } from "./Variable";

/**
 * An environment (`environments/<name>.yaml`).
 */
export type Environment = { name: string, variables: Array<Variable>, };
