// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorCode = "notFound" | "alreadyExists" | "invalidInput" | "notAWorkspace" | "parse" | "io" | "network" | "auth" | "undefinedVariable";
