// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Broad failure category. The UI uses it to pick an icon and a hint.
 */
export type ErrorKind = "invalidRequest" | "dns" | "connect" | "tls" | "proxy" | "timeout" | "protocol" | "io" | "cancelled" | "tooManyRedirects" | "notAllowed";
