// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";

/**
 * A saved response of a request.
 */
export type Example = { name: string, status: number, headers?: Array<KeyValue>, 
/**
 * The response body as text.
 */
body?: string, 
/**
 * The URL the request was sent to, as typed (variables kept), when it differs from the
 * request's own; its query parameters tell mocks which example to answer with.
 */
url?: string, };
