// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilterResult = { 
/**
 * The matches: JSONPath as a pretty JSON array, jq as each output value pretty-printed
 * on its own (like the jq command).
 */
text: string, 
/**
 * How many values matched (or jq produced).
 */
count: number, 
/**
 * Stopped after [`MAX_RESULTS`] values or [`MAX_TEXT`] bytes.
 */
cut: boolean, };
