// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auth } from "./Auth";
import type { KeyValue } from "./KeyValue";
import type { Scripts } from "./Scripts";

/**
 * Folder metadata (`_folder.yaml`). Auth and headers apply to everything inside.
 */
export type FolderMeta = { name: string, seq: number, auth?: Auth, headers?: Array<KeyValue>, scripts?: Scripts, docs?: string, };
