// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How received bytes on a TCP/UDP connection are split into messages.
 */
export type Framing = "raw" | "line" | "lengthPrefixed";
