// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphqlTransport } from "./GraphqlTransport";

/**
 * GraphQL operation (`body.type: graphql`).
 */
export type GraphqlBody = { query?: string, 
/**
 * Variables as JSON text (may contain `{{variables}}`).
 */
variables?: string, operationName?: string, 
/**
 * How a subscription is sent (queries and mutations always go over HTTP).
 */
transport?: GraphqlTransport, 
/**
 * Where a subscription connects. Empty: the request URL (as `ws://`/`wss://` for WebSocket).
 */
subscriptionUrl?: string, 
/**
 * WebSocket: the `connection_init` payload as JSON text (may contain `{{variables}}`).
 */
connectionParams?: string, };
