// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GraphQL operation (`body.type: graphql`).
 */
export type GraphqlBody = { query?: string, 
/**
 * Variables as JSON text (may contain `{{variables}}`).
 */
variables?: string, operationName?: string, };
