// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a GraphQL subscription reaches the server.
 */
export type GraphqlTransport = "websocket" | "websocketLegacy" | "sse";
