// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An introspected GraphQL schema.
 */
export type GraphqlSchema = { 
/**
 * The response's `data` (`{"__schema": …}`), as graphql-js `buildClientSchema` takes it.
 */
data: Record<string, unknown>, 
/**
 * The URL that was introspected (variables resolved).
 */
url: string, 
/**
 * When it was fetched (ms since the Unix epoch).
 */
fetchedAt: number, 
/**
 * Served from the in-memory cache.
 */
cached: boolean, 
/**
 * The server rejected the current introspection query; the older form
 * (no `specifiedByURL`, `isRepeatable`) was used.
 */
legacy: boolean, };
