// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrpcMethod } from "./GrpcMethod";

/**
 * A service and its methods, for the method picker.
 */
export type GrpcService = { 
/**
 * Full name, e.g. `shop.v1.Orders`.
 */
name: string, methods: Array<GrpcMethod>, };
