// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrpcMethod } from "./GrpcMethod";
import type { GrpcOpened } from "./GrpcOpened";

export type GrpcStartResult = { opened: GrpcOpened, 
/**
 * The method called (streaming flags tell the UI whether to offer Send / End).
 */
method: GrpcMethod, unresolved: Array<string>, };
