// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Header } from "./Header";
import type { Timing } from "./Timing";
import type { TlsInfo } from "./TlsInfo";

/**
 * What opening a streaming call established.
 */
export type GrpcOpened = { remoteAddr: string | null, tls: TlsInfo | null, 
/**
 * DNS, connect and TLS; the full timing comes with the `end` event.
 */
timing: Timing, requestHeaders: Array<Header>, };
