// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a gRPC request gets its service definitions.
 */
export type GrpcOptions = { 
/**
 * `.proto` files (relative to the workspace root, or absolute). Empty: server reflection.
 */
protoFiles?: Array<string>, 
/**
 * Folders searched for `import`s (the proto files' folders are always searched).
 */
importPaths?: Array<string>, };
