// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrpcMessage } from "./GrpcMessage";
import type { GrpcStatus } from "./GrpcStatus";
import type { Header } from "./Header";
import type { Timing } from "./Timing";
import type { TlsInfo } from "./TlsInfo";

/**
 * Result of a unary call.
 */
export type GrpcResponse = { status: GrpcStatus, 
/**
 * Received messages (one for a successful unary call).
 */
messages: Array<GrpcMessage>, 
/**
 * Response headers (initial metadata); empty for a trailers-only response.
 */
headers: Array<Header>, trailers: Array<Header>, timing: Timing, remoteAddr: string | null, tls: TlsInfo | null, 
/**
 * Request headers as sent: the gRPC ones, then your metadata.
 */
requestHeaders: Array<Header>, 
/**
 * Problems that did not end the call (e.g. a message that could not be decoded).
 */
warnings: Array<string>, };
