// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";

export type GrpcMessage = { direction: Direction, 
/**
 * The message as JSON (proto3 mapping, default values included).
 */
json: string, 
/**
 * Encoded size in bytes.
 */
size: number, 
/**
 * Unix epoch milliseconds.
 */
timestamp: number, };
