// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrpcMessage } from "./GrpcMessage";
import type { GrpcStatus } from "./GrpcStatus";
import type { Header } from "./Header";
import type { Timing } from "./Timing";

/**
 * Something that happened on a streaming call.
 */
export type GrpcEvent = { "type": "headers", headers: Array<Header>, timestamp: number, } | { "type": "message", message: GrpcMessage, } | { "type": "error", message: string, } | { "type": "end", status: GrpcStatus, trailers: Array<Header>, timing: Timing, };
