// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Final status of a call.
 */
export type GrpcStatus = { code: number, 
/**
 * `OK`, `NOT_FOUND`, …
 */
name: string, 
/**
 * `grpc-message` (percent-decoded).
 */
message: string, 
/**
 * `grpc-status-details-bin`: the `google.rpc.Status` details as JSON, or the raw value.
 */
details: string | null, 
/**
 * Set by Zorvik (cancelled, deadline, connection lost, HTTP error) rather than sent by the server.
 */
local: boolean, };
