// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrpcService } from "./GrpcService";

/**
 * Services of a gRPC request, for the method picker.
 */
export type GrpcDescribeResult = { services: Array<GrpcService>, 
/**
 * `reflection v1`, `reflection v1alpha` or `proto files`.
 */
source: string, };
