// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GrpcMethod = { 
/**
 * `package.Service/Method`: what the request's `method` holds.
 */
path: string, name: string, clientStreaming: boolean, serverStreaming: boolean, inputType: string, outputType: string, 
/**
 * JSON template of the input message (see [`example_json`]).
 */
example: string, };
