// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HawkAlgorithm } from "./HawkAlgorithm";

/**
 * Hawk (https://github.com/mozilla/hawk).
 */
export type HawkConfig = { id: string, key: string, algorithm?: HawkAlgorithm, ext?: string, app?: string, dlg?: string, 
/**
 * Sign the body too (the server must check it).
 */
includePayloadHash?: boolean, };
