// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Request } from "./Request";

export type HistoryEntry = { id: number, requestPath: string | null, method: string, 
/**
 * URL as sent (variables resolved).
 */
url: string, status: number | null, error: string | null, durationMs: number | null, size: number | null, 
/**
 * Unix epoch milliseconds.
 */
createdAt: number, request: Request, };
