// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Header } from "./Header";

/**
 * An HTTP request handled by a mock server.
 */
export type HttpExchange = { method: string, 
/**
 * Path and query as requested.
 */
path: string, httpVersion: string, requestHeaders: Array<Header>, 
/**
 * UTF-8 request body (lossy), capped.
 */
requestBody: string, status: number, responseHeaders: Array<Header>, responseBody: string, durationMs: number, 
/**
 * Name or path of the route that answered; `None` for the fallback.
 */
route: string | null, 
/**
 * Fault injected instead of the normal answer (`error`, `reset`, `hang`) or `proxy`.
 */
note: string | null, };
