// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MockFallback } from "./MockFallback";
import type { MockRoute } from "./MockRoute";

export type HttpMockConfig = { routes: Array<MockRoute>, fallback?: MockFallback, 
/**
 * Base URL of the real backend for the `proxy` fallback.
 */
proxyUrl?: string, 
/**
 * Allow browsers to call the mock from other origins (CORS headers, preflight).
 */
cors?: boolean, };
