// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary returned to the UI after an import.
 */
export type ImportSummary = { name: string, requests: number, folders: number, environments: number, 
/**
 * Collection variables added to the workspace variables.
 */
workspaceVariables: number, warnings: Array<string>, 
/**
 * Path of the created top-level folder (relative to requests/), if any.
 */
folderPath: string | null, };
