// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts of one iteration.
 */
export type IterationSummary = { 
/**
 * 0-based.
 */
iteration: number, requests: number, failed: number, skipped: number, testsPassed: number, testsFailed: number, durationMs: number, };
