// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKeyLocation } from "./ApiKeyLocation";
import type { JwtAlgorithm } from "./JwtAlgorithm";

/**
 * A JWT that Zorvik signs for each request.
 */
export type JwtConfig = { algorithm: JwtAlgorithm, 
/**
 * The shared secret (HS*) or a PEM private key (RS*, PS*, ES*).
 */
secret: string, 
/**
 * The HS* secret is base64.
 */
secretBase64?: boolean, 
/**
 * The claims, as JSON (variables allowed).
 */
payload: string, 
/**
 * Extra header fields, as JSON (`alg` and `typ` are set).
 */
header?: string, 
/**
 * Authorization header prefix; empty sends the bare token.
 */
prefix: string, 
/**
 * Send it in the Authorization header, or as a query parameter.
 */
location?: ApiKeyLocation, 
/**
 * The query parameter's name.
 */
queryParam: string, };
