// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in a key/value table (headers, query params, form fields, variables).
 */
export type KeyValue = { key: string, value: string, enabled?: boolean, description?: string, };
