// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LabInfo = { title: string, goal: string, minutes: number, 
/**
 * What each step asks, in Markdown.
 */
steps: Array<string>, };
