// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LabServerView = { name: string, url: string, 
/**
 * Saved server id (opens it).
 */
serverId: string, };
