// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabServerView } from "./LabServerView";
import type { LabVar } from "./LabVar";
import type { StepView } from "./StepView";

export type LabView = { lesson: string, title: string, goal: string, 
/**
 * Unix epoch milliseconds.
 */
startedAt: number, steps: Array<StepView>, 
/**
 * The "Lab" environment: server addresses and the lab's own values.
 */
vars: Array<LabVar>, servers: Array<LabServerView>, finished: boolean, };
