// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LatencySummary = { min: number, avg: number, p50: number, p90: number, p95: number, p99: number, p999: number, max: number, };
