// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabInfo } from "./LabInfo";
import type { QuestionView } from "./QuestionView";

export type LessonView = { id: string, unit: string, title: string, summary: string, minutes: number, 
/**
 * The reading, in Markdown.
 */
body: string, lab: LabInfo | null, quiz: Array<QuestionView>, prev: string | null, next: string | null, };
