// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LessonState = { id: string, completed: boolean, 
/**
 * Added by an update and not opened yet.
 */
new: boolean, stepsDone: number, labDone: boolean, quizBest: number | null, };
