// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LessonSummary = { id: string, title: string, summary: string, minutes: number, labMinutes: number | null, labSteps: number, questions: number, };
