// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpVersionPref } from "./HttpVersionPref";
import type { LoadModel } from "./LoadModel";
import type { LoadStage } from "./LoadStage";
import type { LoadTarget } from "./LoadTarget";
import type { Threshold } from "./Threshold";

/**
 * A saved load test.
 */
export type LoadTest = { name: string, 
/**
 * Sort position in the sidebar.
 */
seq: number, targets: Array<LoadTarget>, model: LoadModel, stages: Array<LoadStage>, 
/**
 * Closed model: pause after each answer, per user.
 */
thinkTimeMs?: number, 
/**
 * Open model: most requests in flight at once; more are counted as dropped.
 */
maxInFlight?: number, 
/**
 * Reuse connections (HTTP/1.1 keep-alive, HTTP/2 multiplexing). Off: a new
 * connection per request (measures connection setup, uses many ports).
 */
keepAlive?: boolean, 
/**
 * Per-request timeout; the app setting when missing.
 */
timeoutMs?: number, httpVersion?: HttpVersionPref, thresholds?: Array<Threshold>, 
/**
 * CSV or JSON data file (relative to the workspace folder, or absolute): each
 * virtual user takes the next row (user N gets row N % rows); in the
 * arrival-rate model each request takes the next row. Columns are variables.
 */
dataFile?: string, docs?: string, };
