// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadCapture } from "./LoadCapture";

/**
 * A saved request to send, and how often relative to the others.
 */
export type LoadTarget = { 
/**
 * Request path relative to `requests/`.
 */
request: string, weight?: number, enabled?: boolean, 
/**
 * Values saved from this request's responses as variables for the same
 * user's later requests (create an order, then get `/orders/{{orderId}}`).
 */
captures?: Array<LoadCapture>, };
