// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snapshot } from "./Snapshot";
import type { Summary } from "./Summary";

export type LoadEvent = { "type": "snapshot", snapshot: Snapshot, } | { "type": "finished", summary: Summary, };
