// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A saved request to send, and how often relative to the others.
 */
export type LoadTarget = { 
/**
 * Request path relative to `requests/`.
 */
request: string, weight?: number, enabled?: boolean, };
