// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureFrom } from "./CaptureFrom";

/**
 * Save one value from a response as a variable (`{{variable}}`). A capture
 * that finds nothing leaves the variable as it was and counts as a miss.
 */
export type LoadCapture = { variable: string, from: CaptureFrom, 
/**
 * The JSON path, the header name or the regular expression.
 */
path: string, };
