// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadModel } from "./LoadModel";

/**
 * A saved load test in the sidebar.
 */
export type LoadTestNode = { 
/**
 * File stem (`loadtests/<id>.yaml`).
 */
id: string, name: string, model: LoadModel, targets: number, durationSecs: number, seq: number, 
/**
 * Set when the file could not be parsed.
 */
error?: string, };
