// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ramp to `target` over `duration_secs` (linear), then the next stage.
 */
export type LoadStage = { durationSecs: number, target: number, };
