// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoadStarted = { runId: string, plannedMs: number, 
/**
 * `[name, request path]` of the targets, in plan order.
 */
targets: Array<[string, string]>, };
