// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One finished run in the history list.
 */
export type LoadRunRecord = { runId: string, startedAt: number, durationMs: number, passed: boolean, stoppedEarly: boolean, requests: number, rps: number, p95: number, errorRate: number, error: string | null, };
