// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A value a script set, kept on this computer (`vars.local`).
 */
export type LocalValue = { 
/**
 * `environment`, `workspace` or `globals`.
 */
scope: string, 
/**
 * The environment's id, for scope `environment`.
 */
environmentId: string | null, key: string, value: string, };
