// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpCallError } from "./McpCallError";

/**
 * The answer to a call: a result (which may report a failed tool with `isError`), or an error.
 */
export type McpCallResult = { 
/**
 * `tools/call`, `resources/read` or `prompts/get`.
 */
method: string, 
/**
 * The method's parameters as sent.
 */
params: Record<string, unknown>, result: Record<string, unknown> | null, error: McpCallError | null, 
/**
 * A tool result that says the tool failed.
 */
isError: boolean, durationMs: number, };
