// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the server offers (only what its capabilities announce).
 */
export type McpCatalog = { tools: Array<Record<string, unknown>>, resources: Array<Record<string, unknown>>, resourceTemplates: Array<Record<string, unknown>>, prompts: Array<Record<string, unknown>>, 
/**
 * Lists that couldn't be read, in words.
 */
problems: Array<string>, };
