// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A JSON-RPC error answer.
 */
export type McpCallError = { code: number, message: string, data: unknown, };
