// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";

/**
 * Something that happened on the connection.
 */
export type McpEvent = { "type": "message", direction: Direction, 
/**
 * The message as JSON text.
 */
text: string, 
/**
 * Requests and notifications: their method.
 */
method: string | null, 
/**
 * Requests and responses: their id (as JSON).
 */
id: string | null, size: number, timestamp: number, } | { "type": "stderr", text: string, timestamp: number, } | { "type": "info", text: string, timestamp: number, } | { "type": "error", message: string, } | { "type": "closed", reason: string, };
