// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";
import type { McpCallKind } from "./McpCallKind";
import type { McpTransport } from "./McpTransport";

/**
 * Options of MCP requests: how to connect, and the call that Send (and collection runs) make.
 */
export type McpOptions = { transport?: McpTransport, 
/**
 * stdio: environment variables for the program (values may use `{{variables}}`).
 */
env?: Array<KeyValue>, 
/**
 * stdio: the program's working directory, relative to the workspace folder (empty: the folder).
 */
cwd?: string, call?: McpCallKind, 
/**
 * The tool or prompt to call, or the resource URI (a template's `{name}` parts come from
 * the arguments).
 */
name?: string, 
/**
 * The arguments as JSON text (may contain `{{variables}}`).
 */
arguments?: string, };
