// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerInfo } from "./McpServerInfo";

/**
 * What `mcp.connect` established.
 */
export type McpOpened = { info: McpServerInfo, 
/**
 * Variables that were referenced but not defined.
 */
unresolved: Array<string>, };
