// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";

/**
 * The program an MCP request starts, as the user is asked to trust it.
 */
export type McpProgram = { command: string, 
/**
 * The folder it starts in.
 */
cwd: string, env: Array<KeyValue>, 
/**
 * Already trusted for this workspace.
 */
trusted: boolean, };
