// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpPromptMessage = { 
/**
 * `user` (default) or `assistant`.
 */
role?: string, 
/**
 * The message's text; may use `{{args.name}}`.
 */
text: string, };
