// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpPromptArgument } from "./McpPromptArgument";
import type { McpPromptMessage } from "./McpPromptMessage";

/**
 * A prompt of an MCP server.
 */
export type McpPromptMock = { name: string, title?: string, description?: string, arguments?: Array<McpPromptArgument>, messages?: Array<McpPromptMessage>, enabled?: boolean, };
