// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resource of an MCP server. A URI with `{name}` parts is a template: reads fill them in,
 * and its text may use `{{params.name}}`.
 */
export type McpResourceMock = { uri: string, name: string, title?: string, description?: string, 
/**
 * Default `text/plain`.
 */
mimeType?: string, text?: string, enabled?: boolean, };
