// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `initialize` established.
 */
export type McpServerInfo = { 
/**
 * `Streamable HTTP`, `HTTP+SSE` or `stdio`.
 */
transport: string, protocolVersion: string, name: string, title: string | null, version: string, instructions: string | null, 
/**
 * The server's capabilities as it sent them (`tools`, `resources`, `prompts`, …).
 */
capabilities: Record<string, unknown>, 
/**
 * HTTP: the session id the server gave, if any.
 */
sessionId: string | null, 
/**
 * stdio: the program's process id.
 */
pid: number | null, 
/**
 * Connecting and initializing, in milliseconds.
 */
connectMs: number, };
