// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpPromptMock } from "./McpPromptMock";
import type { McpResourceMock } from "./McpResourceMock";
import type { McpToolMock } from "./McpToolMock";

export type McpServerConfig = { 
/**
 * The name clients see (`serverInfo.name`); empty: the server's name.
 */
serverName?: string, version?: string, 
/**
 * Sent with `initialize`: how to use the server.
 */
instructions?: string, tools?: Array<McpToolMock>, resources?: Array<McpResourceMock>, prompts?: Array<McpPromptMock>, 
/**
 * The Streamable HTTP endpoint (HTTP+SSE clients use `/sse`).
 */
path?: string, 
/**
 * Allow browser-based clients on other origins (CORS).
 */
cors?: boolean, };
