// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tool of an MCP server. Its result may use `{{args.name}}` (one argument, text as it is),
 * `{{args}}` (all of them as JSON), dynamic variables and environment variables.
 */
export type McpToolMock = { name: string, title?: string, description?: string, 
/**
 * JSON Schema of the arguments, as JSON text (empty: any object).
 */
inputSchema?: string, 
/**
 * JSON Schema of a structured result, as JSON text: then the result must be JSON, and is
 * also sent as `structuredContent`.
 */
outputSchema?: string, 
/**
 * The result's text.
 */
result?: string, 
/**
 * Answer as a failed tool call (`isError`).
 */
isError?: boolean, delayMs?: number, enabled?: boolean, };
