// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an MCP client reaches its server.
 */
export type McpTransport = "auto" | "streamableHttp" | "sse" | "stdio";
