// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LatencySummary } from "./LatencySummary";
import type { TimingSummary } from "./TimingSummary";

export type MetricsSummary = { 
/**
 * Completed requests (with an answer or an error).
 */
requests: number, 
/**
 * Network errors plus HTTP status ≥ 400.
 */
errors: number, 
/**
 * Percent of requests that failed.
 */
errorRate: number, 
/**
 * Completed requests per second over the elapsed time.
 */
rps: number, bytesIn: number, bytesOut: number, latency: LatencySummary, 
/**
 * `[status, count]`, most frequent first.
 */
statusCodes: Array<[number, number]>, 
/**
 * `[error kind, count]` for network errors (`timeout`, `connect`, …).
 */
errorKinds: Array<[string, number]>, 
/**
 * Open model: iterations not started because `maxInFlight` was reached.
 */
dropped: number, 
/**
 * New connections opened (each new connection pays DNS/TCP/TLS).
 */
connections: number, 
/**
 * Connect, time to first byte, transfer and server-reported time.
 */
timing: TimingSummary, 
/**
 * Captures that found nothing in a response (the variable kept its value).
 */
captureMisses: number, };
