// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";
import type { MockFault } from "./MockFault";

/**
 * One mock route. `path` supports `:name` segments and a trailing `*`.
 * Status, headers and body may use `{{request.params.id}}`,
 * `{{request.query.x}}`, `{{request.headers.x}}`, `{{request.body}}`,
 * `{{request.method}}`, `{{request.path}}`, dynamic variables (`{{$uuid}}`)
 * and the active environment's variables.
 */
export type MockRoute = { name?: string, 
/**
 * HTTP method, or `*` for any.
 */
method: string, path: string, status: number, headers?: Array<KeyValue>, body?: string, delayMs?: number, 
/**
 * Only match requests with these query parameters (empty value = any value).
 */
matchQuery?: Array<KeyValue>, 
/**
 * Only match requests with these headers (empty value = any value).
 */
matchHeaders?: Array<KeyValue>, 
/**
 * Only match requests whose body contains this text.
 */
matchBody?: string, fault?: MockFault, 
/**
 * How often the fault happens, in percent.
 */
faultPercent?: number, enabled?: boolean, };
