// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Replaces a route's normal response.
 */
export type MockFault = "none" | "error" | "reset" | "hang";
