// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A mock server made from a folder or an OpenAPI document.
 */
export type MockCreated = { 
/**
 * Id of the new server (file stem under `servers/`).
 */
id: string, 
/**
 * Number of routes it has.
 */
routes: number, 
/**
 * Parts of an OpenAPI document that could not be used.
 */
warnings: Array<string>, };
