// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MqttSubscription } from "./MqttSubscription";
import type { MqttVersion } from "./MqttVersion";

/**
 * Options of MQTT requests. The message to publish is `body.text`; the
 * username and password come from Basic auth.
 */
export type MqttOptions = { 
/**
 * Empty: a random id per connection.
 */
clientId?: string, version?: MqttVersion, cleanSession?: boolean, keepAliveSecs: number, 
/**
 * Topics subscribed right after connecting.
 */
subscriptions?: Array<MqttSubscription>, 
/**
 * Topic the composer publishes to.
 */
topic?: string, qos: number, retain?: boolean, };
