// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MultipartField = { key: string, 
/**
 * Text value, or a file path when `file` is true.
 */
value: string, file?: boolean, contentType?: string, enabled?: boolean, };
