// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpFamily } from "./IpFamily";

export type NetAddress = { ip: string, 
/**
 * Network prefix length (e.g. 24 for 255.255.255.0).
 */
prefix: number | null, family: IpFamily, 
/**
 * Only usable on the local link (169.254.x.x, fe80::).
 */
linkLocal: boolean, };
