// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetAddress } from "./NetAddress";

export type NetInterface = { name: string, 
/**
 * IPv4 first, then IPv6; link-local addresses last.
 */
addresses: Array<NetAddress>, loopback: boolean, 
/**
 * The interface is up (connected).
 */
up: boolean, };
