// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKeyLocation } from "./ApiKeyLocation";
import type { OAuth1Method } from "./OAuth1Method";

/**
 * OAuth 1.0a request signing (RFC 5849).
 */
export type OAuth1Config = { consumerKey: string, consumerSecret?: string, token?: string, tokenSecret?: string, signatureMethod?: OAuth1Method, 
/**
 * PEM private key, for the RSA methods.
 */
privateKey?: string, callback?: string, verifier?: string, realm?: string, 
/**
 * Send `oauth_version=1.0` (on unless switched off).
 */
includeVersion?: boolean, 
/**
 * Add `oauth_body_hash` for bodies that aren't form data.
 */
includeBodyHash?: boolean, 
/**
 * Parameters in the Authorization header, or in the query string.
 */
location?: ApiKeyLocation, };
