// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientAuthMethod } from "./ClientAuthMethod";
import type { GrantType } from "./GrantType";

export type OAuth2Config = { grantType: GrantType, tokenUrl: string, 
/**
 * Authorization endpoint (authorization code grant only).
 */
authUrl?: string, 
/**
 * Loopback redirect URI registered with the provider (authorization code grant).
 */
redirectUri: string, clientId: string, clientSecret?: string, scope?: string, audience?: string, username?: string, password?: string, clientAuth: ClientAuthMethod, 
/**
 * Use PKCE (S256) for the authorization code grant.
 */
pkce: boolean, 
/**
 * Authorization header prefix; empty sends the bare token.
 */
headerPrefix: string, };
