// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an imported request came from in its OpenAPI document.
 */
export type OpenApiOperation = { 
/**
 * `METHOD /path/{template}` as the document has it, e.g. `GET /pets/{petId}`.
 */
operation: string, 
/**
 * The operation is no longer in the document (found when updating from it).
 */
removed?: boolean, };
