// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The OpenAPI document a folder was imported from, kept in the workspace so its requests'
 * responses can be checked against the documented schemas, and the folder updated later.
 */
export type OpenApiSource = { 
/**
 * The document, relative to the workspace folder (under `specs/`).
 */
spec: string, 
/**
 * Where it was imported from: a URL or a file path (for "Update from OpenAPI").
 */
source?: string, 
/**
 * Check responses against the documented schemas (on unless switched off).
 */
validate?: boolean, };
