// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sent from the UI to a running server (manual mode, or broadcast).
 */
export type OutgoingMessage = { "type": "text", text: string, } | { "type": "binary", base64: string, } | { "type": "event", event: string, data: string, id: string, } | { "type": "emit", event: string, args: string, namespace: string, };
