// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How payloads typed in the UI or stored in files are written.
 */
export type PayloadEncoding = "text" | "hex";
