// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One phase of the requests (milliseconds): how many were measured and
 * their percentiles.
 */
export type PhaseSummary = { 
/**
 * Requests measured (0: no data, the other numbers are 0).
 */
count: number, avg: number, p50: number, p95: number, p99: number, max: number, };
