// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PingSummary = { sent: number, received: number, lossPercent: number, minMs: number | null, avgMs: number | null, maxMs: number | null, 
/**
 * Mean absolute difference between consecutive round trips.
 */
jitterMs: number | null, cancelled: boolean, };
