// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PingMode } from "./PingMode";

/**
 * How a ping run works; the first event of a run.
 */
export type PingStarted = { 
/**
 * `icmp` or `tcp` (never `auto`).
 */
mode: PingMode, address: string, 
/**
 * TCP mode: the port connected to.
 */
port: number | null, 
/**
 * Why TCP is used in auto mode, or other remarks.
 */
note: string | null, };
