// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PingReply = { 
/**
 * 1-based sequence number.
 */
seq: number, 
/**
 * Round-trip time; `None` when there was no reply.
 */
ms: number | null, 
/**
 * IPv4 time-to-live of the reply, where the platform reports it.
 */
ttl: number | null, error: string | null, };
