// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a port did not accept the connection.
 */
export type PortErrorKind = "refused" | "timeout" | "other";
