// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `tools.portCheck` (results follow as events).
 */
export type PortCheckStarted = { 
/**
 * The address being checked (the host is resolved once).
 */
address: string, total: number, };
