// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PortScanSummary = { 
/**
 * The address that was checked.
 */
address: string, 
/**
 * Open ports, ascending.
 */
open: Array<number>, refused: number, timedOut: number, errors: number, 
/**
 * Ports checked (less than `total` when cancelled).
 */
checked: number, total: number, durationMs: number, cancelled: boolean, };
