// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortErrorKind } from "./PortErrorKind";

export type PortResult = { port: number, open: boolean, 
/**
 * Time until the connection opened or failed.
 */
ms: number, error: PortErrorKind | null, 
/**
 * Details for [`PortErrorKind::Other`].
 */
message: string | null, };
