// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EarnedBadge } from "./EarnedBadge";
import type { LessonState } from "./LessonState";

export type ProgressView = { xp: number, level: number, rank: string, 
/**
 * XP at which the current level started, and the next one starts.
 */
levelXp: number, nextLevelXp: number, streak: number, bestStreak: number, 
/**
 * Whether today already counts for the streak.
 */
activeToday: boolean, badges: Array<EarnedBadge>, lessons: Array<LessonState>, 
/**
 * Finished (or tested-out) unit ids.
 */
units: Array<string>, lastLesson: string | null, 
/**
 * Unix epoch milliseconds.
 */
graduatedAt: number | null, completedLessons: number, totalLessons: number, 
/**
 * Lessons an update added that the learner hasn't opened.
 */
newLessons: number, };
