// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Proxy selection mode as chosen in Settings.
 */
export type ProxyMode = { "mode": "none" } | { "mode": "system" } | { "mode": "manual", 
/**
 * e.g. `http://user:pass@proxy.corp:8080`
 */
url: string, 
/**
 * Hosts that bypass the proxy (comma or semicolon separated patterns).
 */
bypass: string, };
