// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionResult } from "./QuestionResult";

export type QuizResult = { results: Array<QuestionResult>, right: number, total: number, passed: boolean, };
