// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * "Send again until …": for polling an endpoint until work is done.
 */
export type RepeatUntil = { 
/**
 * JavaScript checked after each send, after the post-response scripts, e.g.
 * `pm.response.json().status === "done"`. Empty: until the request's tests pass
 * (or, without tests, until the status is below 400).
 */
condition: string, 
/**
 * Pause between sends.
 */
intervalMs: number, 
/**
 * Give up after this long; the request then fails.
 */
timeoutMs: number, };
