// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a WebSocket/TCP/UDP server does with incoming messages.
 */
export type ReplyMode = "echo" | "rules" | "manual" | "discard";
