// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchKind } from "./MatchKind";

/**
 * "When a message matches `pattern`, reply with `reply`." Pattern and reply
 * are text or hex (see the server's `encoding`).
 */
export type ReplyRule = { match: MatchKind, pattern: string, reply: string, delayMs?: number, enabled?: boolean, };
