// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpVersionPref } from "./HttpVersionPref";
import type { RepeatUntil } from "./RepeatUntil";
import type { StreamUntil } from "./StreamUntil";

/**
 * Per-request overrides of the global request settings.
 */
export type RequestSettings = { timeoutMs?: number, followRedirects?: boolean, maxRedirects?: number, verifyTls?: boolean, httpVersion?: HttpVersionPref, decompress?: boolean, 
/**
 * Collection runs: send again until a condition holds (polling).
 */
repeat?: RepeatUntil, 
/**
 * Server-Sent Events in collection runs: when to stop reading.
 */
stream?: StreamUntil, };
