// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestKind = "http" | "websocket" | "sse" | "tcp" | "udp" | "dns" | "mqtt" | "grpc" | "socketio" | "mcp";
