// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpVersionPref } from "./HttpVersionPref";

export type RequestDefaults = { 
/**
 * Whole-request timeout; 0 = no limit.
 */
timeoutMs: number, connectTimeoutMs: number, followRedirects: boolean, maxRedirects: number, verifyTls: boolean, httpVersion: HttpVersionPref, decompress: boolean, 
/**
 * Responses larger than this are truncated.
 */
maxResponseMb: number, 
/**
 * Add User-Agent, Accept and Accept-Encoding automatically.
 */
sendDefaultHeaders: boolean, };
