// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auth } from "./Auth";
import type { Body } from "./Body";
import type { DnsOptions } from "./DnsOptions";
import type { GrpcOptions } from "./GrpcOptions";
import type { KeyValue } from "./KeyValue";
import type { MqttOptions } from "./MqttOptions";
import type { RequestKind } from "./RequestKind";
import type { RequestSettings } from "./RequestSettings";
import type { Scripts } from "./Scripts";
import type { SocketOptions } from "./SocketOptions";

/**
 * A saved request (a `.yaml` file under `requests/`).
 */
export type Request = { name: string, kind?: RequestKind, 
/**
 * Sort position among siblings.
 */
seq: number, method: string, 
/**
 * Raw URL as typed, including the enabled query string.
 */
url: string, 
/**
 * Query params switched off in the UI (not part of `url`).
 */
disabledParams?: Array<KeyValue>, 
/**
 * Values for `:name` path segments.
 */
pathParams?: Array<KeyValue>, headers?: Array<KeyValue>, body?: Body, auth?: Auth, settings?: RequestSettings, 
/**
 * TCP/UDP options.
 */
socket?: SocketOptions, dns?: DnsOptions, mqtt?: MqttOptions, grpc?: GrpcOptions, scripts?: Scripts, docs?: string, };
