// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpVersionPref } from "./HttpVersionPref";

/**
 * Per-request overrides of the global request settings.
 */
export type RequestSettings = { timeoutMs?: number, followRedirects?: boolean, maxRedirects?: number, verifyTls?: boolean, httpVersion?: HttpVersionPref, decompress?: boolean, };
