// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response body prepared for display.
 */
export type ResponseBody = { 
/**
 * `text`, `image` or `binary`.
 */
kind: string, contentType: string | null, 
/**
 * Decoded size in bytes.
 */
size: number, 
/**
 * Text content (UTF-8, lossy) for text bodies, capped for display.
 */
text: string | null, 
/**
 * Pretty-printed JSON when the body is JSON.
 */
pretty: string | null, 
/**
 * Base64 data for image previews.
 */
base64: string | null, 
/**
 * Only part of the body is shown; save it to a file to see everything.
 */
displayTruncated: boolean, 
/**
 * The response exceeded the size limit and was cut while downloading.
 */
downloadTruncated: boolean, decodeWarning: string | null, };
