// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CookieInfo } from "./CookieInfo";
import type { Header } from "./Header";
import type { RedirectHop } from "./RedirectHop";
import type { SentRequest } from "./SentRequest";
import type { TlsInfo } from "./TlsInfo";

export type ResponseMeta = { status: number, statusText: string, httpVersion: string, headers: Array<Header>, 
/**
 * Final URL after redirects.
 */
url: string, remoteAddr: string | null, tls: TlsInfo | null, redirects: Array<RedirectHop>, request: SentRequest, headersSize: number, cookies: Array<CookieInfo>, };
