// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an action earned, for the celebration.
 */
export type Rewards = { xp: number, 
/**
 * What earned the XP ("Step done", "Lesson complete", …).
 */
reasons: Array<string>, 
/**
 * The new level, when it went up.
 */
levelUp: number | null, 
/**
 * The new rank, when it changed.
 */
rankUp: string | null, badges: Array<string>, lessonCompleted: string | null, unitCompleted: string | null, graduated: boolean, };
