// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunResult } from "./RunResult";
import type { RunSummary } from "./RunSummary";

/**
 * Events of a run (`runner {runId, event}`).
 */
export type RunEvent = { "type": "started", name: string, total: number, iterations: number, } | { "type": "result", result: RunResult, } | { "type": "finished", summary: RunSummary, };
