// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerKind } from "./ServerKind";
import type { ServerStats } from "./ServerStats";

/**
 * A running server as the UI lists it (title bar, sidebar, server tab).
 */
export type RunningServerInfo = { runId: string, 
/**
 * Workspace folder the server belongs to.
 */
workspacePath: string, workspaceName: string, 
/**
 * Saved server id (file stem under `servers/`).
 */
serverId: string, name: string, kind: ServerKind, 
/**
 * Address clients use, e.g. `http://127.0.0.1:3000`.
 */
url: string, host: string, port: number, tls: boolean, 
/**
 * Unix epoch milliseconds.
 */
startedAt: number, stats: ServerStats, };
