// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsoleEntry } from "./ConsoleEntry";
import type { RequestKind } from "./RequestKind";
import type { TestResult } from "./TestResult";

/**
 * One request of one iteration.
 */
export type RunResult = { 
/**
 * 0-based.
 */
iteration: number, 
/**
 * Path relative to `requests/`.
 */
path: string, name: string, kind: RequestKind, method: string, 
/**
 * The URL as sent, with secret values shown as `{{name}}`; the saved URL when nothing was sent.
 */
url: string, status: number | null, durationMs: number | null, 
/**
 * Response body bytes.
 */
size: number | null, tests: Array<TestResult>, 
/**
 * Console output of the scripts (the first lines).
 */
console: Array<ConsoleEntry>, 
/**
 * Why there is no response: network or resolve error, pre-request script error.
 */
error: string | null, 
/**
 * Post-response scripts that failed.
 */
scriptErrors: Array<string>, 
/**
 * Variables that were referenced but not defined.
 */
unresolved: Array<string>, passed: boolean, 
/**
 * Not a kind the runner sends: not sent.
 */
skipped: boolean, 
/**
 * Why it was skipped.
 */
skipReason?: string, 
/**
 * Sends made for "repeat until" (the result is the last one's).
 */
attempts?: number, };
