// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunResult } from "./RunResult";
import type { RunSummary } from "./RunSummary";

/**
 * The JSON report: summary and every result.
 */
export type RunReport = { summary: RunSummary, results: Array<RunResult>, };
