// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IterationSummary } from "./IterationSummary";

export type RunSummary = { 
/**
 * The folder's name, or the workspace's for the whole collection.
 */
name: string, environment: string | null, 
/**
 * Unix epoch milliseconds.
 */
startedAt: number, durationMs: number, 
/**
 * Iterations planned.
 */
iterations: number, 
/**
 * Requests sent or tried (skipped ones not counted).
 */
requests: number, 
/**
 * Requests that failed.
 */
failed: number, skipped: number, testsPassed: number, testsFailed: number, testsSkipped: number, 
/**
 * Stopped by the user.
 */
stopped: boolean, 
/**
 * Stopped at the first failure (`stopOnFailure`).
 */
bailed: boolean, 
/**
 * Why the run ended early otherwise (e.g. a `setNextRequest` loop).
 */
error: string | null, 
/**
 * No request failed and the run was not cut short by an error.
 */
passed: boolean, perIteration: Array<IterationSummary>, 
/**
 * Results left out of `results`: a report keeps the first 50,000, then failed ones only (counted above).
 */
omitted: number, };
