// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScriptFailure = { 
/**
 * Which script: "Pre-request script of folder 'Users'".
 */
script: string, message: string, line: number | null, };
