// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsoleEntry } from "./ConsoleEntry";
import type { ScriptFailure } from "./ScriptFailure";
import type { TestResult } from "./TestResult";

/**
 * What the scripts of one send produced.
 */
export type ScriptReport = { tests: Array<TestResult>, console: Array<ConsoleEntry>, 
/**
 * Scripts that stopped with an error (a pre-request one also stops the send).
 */
errors: Array<ScriptFailure>, };
