// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * JavaScript run before sending and after the response (Postman-compatible `pm` API).
 */
export type Scripts = { preRequest?: string, postResponse?: string, };
