// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResponseBody } from "./ResponseBody";
import type { ResponseMeta } from "./ResponseMeta";
import type { ScriptReport } from "./ScriptReport";
import type { Timing } from "./Timing";

export type SendResult = { 
/**
 * Handle for `response.save`.
 */
responseId: string, meta: ResponseMeta, timing: Timing, body: ResponseBody, bodyWireSize: number, 
/**
 * Variables that were referenced but not defined.
 */
unresolved: Array<string>, 
/**
 * Tests, console output and errors of the request's scripts, when any ran.
 */
scripts?: ScriptReport, };
