// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Header } from "./Header";

/**
 * What actually went over the wire for the final hop.
 */
export type SentRequest = { method: string, url: string, httpVersion: string, headers: Array<Header>, bodySize: number, proxy: string | null, };
