// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TLS for a listener. Without certificate paths a self-signed certificate for
 * `localhost` is generated (clients must trust it or skip verification).
 */
export type ServerTls = { enabled: boolean, 
/**
 * PEM certificate chain.
 */
certPath?: string, 
/**
 * PEM private key.
 */
keyPath?: string, };
