// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerStats } from "./ServerStats";
import type { TrafficEntry } from "./TrafficEntry";

/**
 * Events of one running server.
 */
export type ServerEvent = { "type": "traffic", entry: TrafficEntry, } | { "type": "stats", stats: ServerStats, } | { "type": "stopped", error: string | null, };
