// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerStats = { connectionsOpen: number, connectionsTotal: number, 
/**
 * HTTP requests, DNS queries, UDP datagrams, WebSocket/SSE/TCP messages received.
 */
requests: number, bytesIn: number, bytesOut: number, errors: number, };
