// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerKind } from "./ServerKind";

/**
 * A saved server in the sidebar.
 */
export type ServerNode = { 
/**
 * File stem, used as the server id (`servers/<id>.yaml`).
 */
id: string, name: string, kind: ServerKind, host: string, port: number, tls: boolean, seq: number, autoStart: boolean, 
/**
 * Set when the file could not be parsed.
 */
error?: string, };
