// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DnsServerConfig } from "./DnsServerConfig";
import type { HttpMockConfig } from "./HttpMockConfig";
import type { McpServerConfig } from "./McpServerConfig";
import type { ServerKind } from "./ServerKind";
import type { ServerTls } from "./ServerTls";
import type { SocketIoServerConfig } from "./SocketIoServerConfig";
import type { SocketServerConfig } from "./SocketServerConfig";
import type { SseServerConfig } from "./SseServerConfig";
import type { TcpProxyConfig } from "./TcpProxyConfig";
import type { WsServerConfig } from "./WsServerConfig";

/**
 * A saved server. Only the section for its `kind` is used; the others are
 * kept, so switching the kind in the UI never loses what was set up.
 */
export type Server = { name: string, kind: ServerKind, 
/**
 * Sort position in the sidebar.
 */
seq: number, 
/**
 * Address to listen on: `127.0.0.1` (only this computer, the default) or
 * `0.0.0.0` (other devices too).
 */
host: string, 
/**
 * Port (0: any free port).
 */
port: number, tls?: ServerTls, 
/**
 * Start when the workspace is opened.
 */
autoStart?: boolean, http?: HttpMockConfig, websocket?: WsServerConfig, sse?: SseServerConfig, 
/**
 * TCP and UDP servers.
 */
socket?: SocketServerConfig, dns?: DnsServerConfig, proxy?: TcpProxyConfig, socketio?: SocketIoServerConfig, mcp?: McpServerConfig, docs?: string, };
