// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSettings } from "./AgentSettings";
import type { Appearance } from "./Appearance";
import type { ProxyMode } from "./ProxyMode";
import type { RequestDefaults } from "./RequestDefaults";
import type { Theme } from "./Theme";
import type { TlsSettings } from "./TlsSettings";

export type Settings = { theme: Theme, appearance: Appearance, request: RequestDefaults, proxy: ProxyMode, tls: TlsSettings, 
/**
 * History entries kept per workspace.
 */
historyLimit: number, 
/**
 * Keep cookies from responses and send them on later requests.
 */
cookieJar: boolean, 
/**
 * Let requests send body files from outside the workspace folder.
 */
filesOutsideWorkspace: boolean, 
/**
 * Time limit of one pre-request or post-response script.
 */
scriptTimeoutMs: number, agents: AgentSettings, };
