// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsSummary } from "./MetricsSummary";
import type { RunPhase } from "./RunPhase";
import type { TargetSummary } from "./TargetSummary";
import type { ThresholdResult } from "./ThresholdResult";
import type { TimePoint } from "./TimePoint";

/**
 * Sent about 4 times a second while a test runs.
 */
export type Snapshot = { phase: RunPhase, elapsedMs: number, plannedMs: number, 
/**
 * Users (closed) or requests in flight (open) right now.
 */
active: number, 
/**
 * Current stage target (users or requests per second).
 */
target: number, totals: MetricsSummary, targets: Array<TargetSummary>, 
/**
 * Seconds completed since the previous snapshot (append to the charts).
 */
points: Array<TimePoint>, thresholds: Array<ThresholdResult>, 
/**
 * CPU used by this app (percent of one core × cores, 0–100 per core summed), when known.
 */
cpuPercent: number | null, };
