// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Languages a request can be exported to as code.
 */
export type SnippetLanguage = "kotlin" | "swift" | "javascript" | "javascriptAxios" | "python" | "pythonHttpx" | "go" | "java" | "csharp" | "php" | "ruby" | "rust" | "dart" | "c" | "powerShell" | "httpie" | "wget";
