// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplyMode } from "./ReplyMode";
import type { SocketIoRule } from "./SocketIoRule";

export type SocketIoServerConfig = { 
/**
 * Echo: emit every event back to its sender (and acknowledge with its arguments).
 */
mode?: ReplyMode, 
/**
 * Emitted to each client right after it connects (empty: nothing).
 */
greetingEvent?: string, greetingArgs?: string, rules?: Array<SocketIoRule>, 
/**
 * Where the server answers (socket.io's `path` option).
 */
path?: string, 
/**
 * Allow browsers on other origins to connect (CORS for long-polling).
 */
cors?: boolean, };
