// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchKind } from "./MatchKind";

/**
 * "When a client emits `event` (and its arguments match), acknowledge and/or emit a reply."
 * Arguments are JSON: an array for several, or a single value. Replies may use templates
 * (`{{event.args}}`, `{{event.arg0}}`, `{{$uuid}}`, environment variables).
 */
export type SocketIoRule = { 
/**
 * Event name, or `*` for any.
 */
event: string, 
/**
 * How the arguments (as JSON text) must match `pattern`.
 */
match?: MatchKind, pattern?: string, 
/**
 * Arguments of the acknowledgement, when the client asks for one (empty: no arguments).
 */
ack?: string, 
/**
 * Event to emit back (empty: none).
 */
replyEvent?: string, replyArgs?: string, 
/**
 * Emit the reply to every client of the namespace, not just the sender.
 */
broadcast?: boolean, delayMs?: number, enabled?: boolean, };
