// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something to send on a socket session.
 */
export type SocketOutgoing = { "type": "text", text: string, } | { "type": "binary", base64: string, } | { "type": "publish", topic: string, text: string | null, base64: string | null, qos: number, retain: boolean, } | { "type": "subscribe", topic: string, qos: number, } | { "type": "unsubscribe", topic: string, } | { "type": "emit", event: string, args: string, base64: string | null, 
/**
 * Ask the server to acknowledge.
 */
ack: boolean, };
