// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timing } from "./Timing";
import type { TlsInfo } from "./TlsInfo";

/**
 * What a socket connect established (shown when the connection opens).
 */
export type SocketOpened = { 
/**
 * `TCP`, `TLS`, `UDP`, `MQTT 3.1.1`, …
 */
protocol: string, remoteAddr: string | null, localAddr: string | null, tls: TlsInfo | null, timing: Timing, };
