// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SocketIoTransport } from "./SocketIoTransport";

/**
 * Options of Socket.IO requests (Socket.IO 3 and 4, Engine.IO 4).
 */
export type SocketIoOptions = { 
/**
 * Where the server answers (socket.io's `path` option).
 */
path?: string, 
/**
 * The connection's `auth` payload as JSON text (may contain `{{variables}}`).
 */
auth?: string, transport?: SocketIoTransport, 
/**
 * The event the composer emits.
 */
event?: string, 
/**
 * The composer asks the server to acknowledge.
 */
ack?: boolean, };
