// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a Socket.IO client reaches the server.
 */
export type SocketIoTransport = "auto" | "websocket" | "polling";
