// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";

export type SocketEvent = { "type": "message", direction: Direction, 
/**
 * UTF-8 payload when it decodes.
 */
text: string | null, 
/**
 * Base64 payload otherwise.
 */
base64: string | null, size: number, 
/**
 * Unix epoch milliseconds.
 */
timestamp: number, 
/**
 * UDP: the other side's address.
 */
peer: string | null, 
/**
 * MQTT: the message topic.
 */
topic: string | null, 
/**
 * MQTT: QoS and retain flag, e.g. `QoS 1 · retained`.
 */
detail: string | null, } | { "type": "info", text: string, timestamp: number, } | { "type": "error", message: string, } | { "type": "closed", reason: string, byClient: boolean, };
