// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Framing } from "./Framing";
import type { LineEnding } from "./LineEnding";
import type { PayloadEncoding } from "./PayloadEncoding";
import type { ReplyMode } from "./ReplyMode";
import type { ReplyRule } from "./ReplyRule";

export type SocketServerConfig = { mode?: ReplyMode, 
/**
 * TCP: sent to each client right after it connects.
 */
greeting?: string, rules?: Array<ReplyRule>, 
/**
 * Encoding of greeting, rule patterns and replies.
 */
encoding?: PayloadEncoding, 
/**
 * TCP: how incoming bytes are split into messages.
 */
framing?: Framing, lengthBytes?: number, 
/**
 * Appended to text replies.
 */
lineEnding?: LineEnding, };
