// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SocketOpened } from "./SocketOpened";

export type SocketConnectResult = { opened: SocketOpened, 
/**
 * Variables that were referenced but not defined.
 */
unresolved: Array<string>, };
