// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Framing } from "./Framing";
import type { LineEnding } from "./LineEnding";

/**
 * Options of TCP and UDP requests (and of TCP/UDP servers).
 */
export type SocketOptions = { framing?: Framing, 
/**
 * Length prefix size for `lengthPrefixed` framing: 1, 2 or 4 bytes.
 */
lengthBytes?: number, lineEnding?: LineEnding, 
/**
 * UDP: allow sending to broadcast addresses.
 */
broadcast?: boolean, };
