// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecChange } from "./SpecChange";

/**
 * What an update does (or would do: the preview).
 */
export type SpecUpdate = { added: Array<SpecChange>, changed: Array<SpecChange>, 
/**
 * No longer in the document: kept and marked.
 */
removed: Array<SpecChange>, 
/**
 * Back in the document after being marked removed.
 */
restored: Array<SpecChange>, unchanged: number, 
/**
 * Variables added to the folder's environment (path parameters of new operations).
 */
variables: Array<string>, warnings: Array<string>, 
/**
 * Whether it was written (false for a preview).
 */
applied: boolean, };
