// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One operation in an update.
 */
export type SpecChange = { 
/**
 * `METHOD /path` as the document has it.
 */
operation: string, name: string, 
/**
 * The saved request (none yet for added ones).
 */
path: string | null, 
/**
 * Fields the update changes.
 */
fields: Array<string>, 
/**
 * Fields both the document and the user changed: the user's version stays.
 */
kept: Array<string>, };
