// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SseEvent = { 
/**
 * `message` when the server sent no `event:` field.
 */
event: string, data: string, 
/**
 * Last event ID in effect when this event was dispatched.
 */
id: string | null, 
/**
 * Reconnection time requested by the server, in milliseconds.
 */
retry: number | null, };
