// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SseEventTemplate = { 
/**
 * Event name (empty: the default `message`).
 */
event?: string, data: string, id?: string, };
