// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SseEventTemplate } from "./SseEventTemplate";

export type SseServerConfig = { 
/**
 * Sent to each client in order after it connects.
 */
events?: Array<SseEventTemplate>, 
/**
 * Pause between events (0: all at once).
 */
intervalMs?: number, 
/**
 * Start over after the last event.
 */
repeat?: boolean, };
