// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SseEvent } from "./SseEvent";

export type SseStreamEvent = { "type": "event", event: SseEvent, timestamp: number, } | { "type": "error", message: string, } | { "type": "closed", reason: string, };
