// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StepView = { 
/**
 * What to do, in Markdown.
 */
text: string, 
/**
 * The hints opened so far.
 */
hints: Array<string>, hintsTotal: number, done: boolean, assisted: boolean, 
/**
 * The step asks for a typed answer.
 */
answer: boolean, 
/**
 * The lab calls the learner's server: "Check now" helps after changing it.
 */
probe: boolean, };
