// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When reading a Server-Sent Events stream stops: a named event, a number of events,
 * the server closing it, or a time limit, whichever comes first.
 */
export type StreamUntil = { 
/**
 * Stop after the first event with this name (`message` for events without a name).
 */
event?: string, 
/**
 * Stop after this many events (0: no limit but the time).
 */
maxEvents: number, 
/**
 * Stop after this long.
 */
timeoutMs: number, };
