// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentEvent } from "./AgentEvent";
import type { GrpcEvent } from "./GrpcEvent";
import type { LoadEvent } from "./LoadEvent";
import type { RunEvent } from "./RunEvent";
import type { ServerEvent } from "./ServerEvent";
import type { Settings } from "./Settings";
import type { SocketEvent } from "./SocketEvent";
import type { SseStreamEvent } from "./SseStreamEvent";
import type { ToolEvent } from "./ToolEvent";
import type { WsEvent } from "./WsEvent";

/**
 * Events pushed to the UI.
 */
export type StreamEvent = { "type": "ws", connId: string, event: WsEvent, } | { "type": "sse", connId: string, event: SseStreamEvent, } | { "type": "workspaceChanged", paths: Array<string>, } | { "type": "openUrl", url: string, } | { "type": "socket", connId: string, event: SocketEvent, } | { "type": "server", runId: string, event: ServerEvent, } | { "type": "tool", runId: string, event: ToolEvent, } | { "type": "quitRequested", running: number, loadTest: boolean, } | { "type": "load", runId: string, event: LoadEvent, } | { "type": "grpc", sessionId: string, event: GrpcEvent, } | { "type": "runner", runId: string, event: RunEvent, 
/**
 * An AI agent started the run (the UI shows it only when following agents).
 */
agent?: boolean, } | { "type": "agent", event: AgentEvent, } | { "type": "settingsChanged", settings: Settings, } | { "type": "batch", events: Array<StreamEvent>, };
