// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResponseMeta } from "./ResponseMeta";
import type { Timing } from "./Timing";

export type StreamOpened = { meta: ResponseMeta, timing: Timing, unresolved: Array<string>, };
