// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsSummary } from "./MetricsSummary";
import type { TargetSummary } from "./TargetSummary";
import type { ThresholdResult } from "./ThresholdResult";
import type { TimePoint } from "./TimePoint";

/**
 * The result of a run.
 */
export type Summary = { 
/**
 * Unix epoch milliseconds.
 */
startedAt: number, durationMs: number, totals: MetricsSummary, targets: Array<TargetSummary>, points: Array<TimePoint>, thresholds: Array<ThresholdResult>, 
/**
 * Every threshold passed (and the run was not aborted by an error).
 */
passed: boolean, 
/**
 * Stopped before the planned end.
 */
stoppedEarly: boolean, 
/**
 * Why the run could not continue, if it failed.
 */
error: string | null, 
/**
 * Highest CPU seen, when known.
 */
peakCpuPercent: number | null, };
