// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsSummary } from "./MetricsSummary";

export type TargetSummary = { 
/**
 * Request name.
 */
name: string, 
/**
 * Request path (relative to `requests/`).
 */
request: string, metrics: MetricsSummary, };
