// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TcpProxyConfig = { 
/**
 * `host:port` every client connection is relayed to.
 */
target: string, 
/**
 * Connect to the target with TLS (clients still talk plain TCP to the relay).
 */
upstreamTls?: boolean, };
