// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `pm.test`.
 */
export type TestResult = { name: string, passed: boolean, 
/**
 * `pm.test.skip` (neither passed nor failed).
 */
skipped: boolean, error: string | null, };
