// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThresholdMetric } from "./ThresholdMetric";
import type { ThresholdOp } from "./ThresholdOp";

/**
 * "p95 < 300" — fails the run when it does not hold at the end.
 */
export type Threshold = { metric: ThresholdMetric, op: ThresholdOp, value: number, 
/**
 * Only this target (request path); the whole test when missing.
 */
target?: string, enabled?: boolean, };
