// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThresholdMetric = "p50" | "p90" | "p95" | "p99" | "p999" | "avg" | "max" | "errorRate" | "rps";
