// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThresholdMetric } from "./ThresholdMetric";
import type { ThresholdOp } from "./ThresholdOp";

export type ThresholdResult = { 
/**
 * E.g. `p95 < 300 ms` or `errorRate < 1 % · Get users`.
 */
label: string, metric: ThresholdMetric, op: ThresholdOp, value: number, target: string | null, 
/**
 * `None` until there is data.
 */
actual: number | null, passed: boolean, };
