// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One second of the run, for the charts.
 */
export type TimePoint = { 
/**
 * Seconds since the start.
 */
second: number, 
/**
 * Requests completed in this second.
 */
rps: number, errors: number, p50: number, p95: number, p99: number, 
/**
 * Users (closed model) or requests in flight (open model) at the end of the second.
 */
active: number, 
/**
 * Stage target: users at the end of the second, or the average request
 * rate over the second.
 */
target: number, };
