// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase durations in milliseconds.
 */
export type Timing = { 
/**
 * Time spent on earlier redirect hops.
 */
redirectMs: number, dnsMs: number, connectMs: number, tlsMs: number, 
/**
 * Request sent until the first response byte (server processing time).
 */
ttfbMs: number, downloadMs: number, totalMs: number, };
