// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PhaseSummary } from "./PhaseSummary";

/**
 * Where the time of the requests went.
 */
export type TimingSummary = { 
/**
 * Opening a new connection: DNS, TCP, proxy tunnel and TLS. Only requests
 * that opened one are measured.
 */
connect: PhaseSummary, 
/**
 * Request sent until the first byte of the response: the server's time
 * plus one network round trip.
 */
ttfb: PhaseSummary, 
/**
 * First byte until the last byte of the response.
 */
transfer: PhaseSummary, 
/**
 * What servers reported in a `Server-Timing` header (its `total`, else
 * the sum of its durations); `count` 0 when no response had one.
 */
server: PhaseSummary, };
