// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TlsCipherSupport = { 
/**
 * rustls name, e.g. `TLS13_AES_128_GCM_SHA256`.
 */
name: string, version: string, 
/**
 * `None`: no answer (timeout, connection error, time limit).
 */
accepted: boolean | null, forwardSecrecy: boolean, detail: string | null, };
