// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TlsCertificate = { subject: string, commonName: string | null, issuer: string, issuerCommonName: string | null, 
/**
 * RFC 3339.
 */
notBefore: string, notAfter: string, 
/**
 * Whole days until `not_after` (negative once expired).
 */
daysLeft: number, notYetValid: boolean, subjectAltNames: Array<string>, 
/**
 * `RSA`, `EC`, `Ed25519`, …
 */
keyType: string, keyBits: number | null, 
/**
 * EC curve, e.g. `P-256`.
 */
keyCurve: string | null, signatureAlgorithm: string, 
/**
 * SHA-256 of the DER certificate, `AB:CD:…`.
 */
sha256: string, serial: string, isCa: boolean, selfSigned: boolean, 
/**
 * Set when the certificate could not be parsed (other fields are then empty).
 */
parseError: string | null, };
