// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CertificateInfo } from "./CertificateInfo";

/**
 * What was negotiated on a TLS connection, shown in the response "Info" tab.
 */
export type TlsInfo = { version: string, cipher: string, alpn: string | null, certificate: CertificateInfo | null, };
