// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TlsOptions = { 
/**
 * Verify the server certificate chain and host name.
 */
verify: boolean, 
/**
 * Extra trusted root CA certificates (PEM file), added to the OS trust store.
 */
caCertPath: string | null, 
/**
 * Client certificate for mutual TLS (PEM file with one or more certificates).
 */
clientCertPath: string | null, 
/**
 * Private key for the client certificate (PEM file).
 */
clientKeyPath: string | null, };
