// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TlsCertificate } from "./TlsCertificate";
import type { TlsCipherSupport } from "./TlsCipherSupport";
import type { TlsVersionSupport } from "./TlsVersionSupport";
import type { TlsWarning } from "./TlsWarning";

export type TlsReport = { host: string, port: number, 
/**
 * Name sent in SNI (none for IP addresses) and checked against the certificate.
 */
serverName: string, 
/**
 * Address connected to (the proxy's when tunnelling).
 */
remoteAddr: string, 
/**
 * `host:port` of the HTTP proxy used, if any.
 */
proxy: string | null, version: string, cipher: string, 
/**
 * Key exchange group, e.g. `X25519`.
 */
keyExchange: string | null, alpn: string | null, 
/**
 * The OS trust store (plus the CA from Settings) accepts the chain for this name.
 */
trusted: boolean, 
/**
 * Why the chain is not trusted.
 */
trustError: string | null, hostnameMatches: boolean, 
/**
 * The server stapled an OCSP response.
 */
ocspStapled: boolean, 
/**
 * Certificates as sent by the server, the server's own first.
 */
chain: Array<TlsCertificate>, 
/**
 * TLS 1.3 … TLS 1.0; `supported` is `None` when not tested.
 */
versions: Array<TlsVersionSupport>, ciphers: Array<TlsCipherSupport>, 
/**
 * Most severe first.
 */
warnings: Array<TlsWarning>, 
/**
 * TCP connect + TLS handshake of the first connection.
 */
handshakeMs: number, durationMs: number, };
