// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TlsSettings = { 
/**
 * Extra trusted CA certificate (PEM). Empty = OS trust store only.
 */
caCertPath: string, clientCertPath: string, clientKeyPath: string, };
