// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TlsVersionSupport = { 
/**
 * `TLS 1.3`, `TLS 1.2`, `TLS 1.1`, `TLS 1.0`.
 */
version: string, 
/**
 * `None`: not tested or no answer.
 */
supported: boolean | null, detail: string | null, };
