// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TlsWarningLevel } from "./TlsWarningLevel";

export type TlsWarning = { level: TlsWarningLevel, 
/**
 * Stable id: `untrusted`, `expired`, `notYetValid`, `hostnameMismatch`,
 * `chainExpired`, `expiresSoon`, `selfSigned`, `weakKey`, `weakSignature`,
 * `noForwardSecrecy`, `noTls13`.
 */
code: string, message: string, };
