// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenStatus = { hasToken: boolean, 
/**
 * First/last characters only.
 */
tokenPreview: string | null, expiresAt: number | null, scope: string | null, hasRefreshToken: boolean, };
