// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenSet = { accessToken: string, tokenType: string, 
/**
 * Unix epoch milliseconds; `None` when the server gave no expiry.
 */
expiresAt: number | null, refreshToken: string | null, scope: string | null, obtainedAt: number, };
