// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PingReply } from "./PingReply";
import type { PingStarted } from "./PingStarted";
import type { PingSummary } from "./PingSummary";
import type { PortResult } from "./PortResult";
import type { PortScanSummary } from "./PortScanSummary";

/**
 * Progress of a streaming tool run. A port check ends with `portsDone`, a
 * ping with `pingDone` (also when cancelled).
 */
export type ToolEvent = { "type": "portResult" } & PortResult | { "type": "portsDone" } & PortScanSummary | { "type": "pingStarted" } & PingStarted | { "type": "pingReply" } & PingReply | { "type": "pingDone" } & PingSummary;
