// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpExchange } from "./HttpExchange";
import type { TrafficDirection } from "./TrafficDirection";
import type { TrafficKind } from "./TrafficKind";

export type TrafficEntry = { id: number, 
/**
 * Unix epoch milliseconds.
 */
timestamp: number, kind: TrafficKind, 
/**
 * Connection id (per server), when the entry belongs to one.
 */
conn: number | null, 
/**
 * Client address.
 */
peer: string | null, direction: TrafficDirection | null, 
/**
 * One line for the log.
 */
summary: string, 
/**
 * Payload as UTF-8 when it decodes (or details, e.g. a DNS answer).
 */
text: string | null, 
/**
 * Payload as base64 when it is not UTF-8.
 */
base64: string | null, 
/**
 * Payload size in bytes.
 */
size: number, 
/**
 * Only the first 64 KB of the payload is kept.
 */
truncated: boolean, http: HttpExchange | null, };
