// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKind } from "./NodeKind";
import type { RequestKind } from "./RequestKind";

/**
 * Collection tree node for the sidebar.
 */
export type TreeNode = { kind: NodeKind, 
/**
 * Path relative to the workspace `requests/` directory, `/`-separated.
 */
path: string, name: string, seq: number, method?: string, requestKind?: RequestKind, 
/**
 * An HTTP request with a GraphQL body (the sidebar shows `GQL` instead of the method).
 */
graphql?: boolean, 
/**
 * Set when the file could not be parsed.
 */
error?: string, 
/**
 * An imported request whose operation is no longer in its OpenAPI document.
 */
removedFromSpec?: boolean, 
/**
 * A folder imported from an OpenAPI document the workspace keeps (it can be updated from it).
 */
fromSpec?: boolean, children: Array<TreeNode>, };
