// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BadgeView } from "./BadgeView";
import type { LessonSummary } from "./LessonSummary";

export type UnitView = { id: string, title: string, summary: string, color: string, image: string, capstone: boolean, badge: BadgeView, lessons: Array<LessonSummary>, };
