// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the app keeps itself up to date (Settings → Updates). The only thing it does is read
 * the release list file on GitHub; nothing about the user or their work is sent.
 */
export type UpdateMode = "automatic" | "notify" | "off";
