// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which releases the app updates to.
 */
export type UpdateChannel = "stable" | "nightly";
