// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A variable in the workspace or an environment.
 */
export type Variable = { key: string, 
/**
 * Empty in the file for secrets; the real value lives in the local secret store.
 */
value: string, enabled?: boolean, secret?: boolean, };
