// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VariableInfo = { key: string, 
/**
 * Masked for secrets.
 */
value: string, 
/**
 * `environment`, `workspace` or `globals`.
 */
source: string, secret: boolean, 
/**
 * The value was set by a script and is kept on this computer only.
 */
local: boolean, };
