// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auth } from "./Auth";
import type { KeyValue } from "./KeyValue";
import type { Scripts } from "./Scripts";
import type { Variable } from "./Variable";

/**
 * Workspace root metadata (`zorvik.yaml`).
 */
export type WorkspaceMeta = { version: number, 
/**
 * Stable id used to key local-only data (secrets, active environment).
 */
id: string, name: string, variables?: Array<Variable>, 
/**
 * Default auth for requests set to "inherit".
 */
auth?: Auth, headers?: Array<KeyValue>, scripts?: Scripts, docs?: string, };
