// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentEntry } from "./EnvironmentEntry";
import type { TreeNode } from "./TreeNode";
import type { WorkspaceMeta } from "./WorkspaceMeta";

export type WorkspaceInfo = { path: string, 
/**
 * Variables include secret values from the local secret store.
 */
meta: WorkspaceMeta, tree: Array<TreeNode>, environments: Array<EnvironmentEntry>, activeEnvironment: string | null, };
