// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";
import type { WsMessageKind } from "./WsMessageKind";

export type WsEvent = { "type": "message", direction: Direction, kind: WsMessageKind, 
/**
 * UTF-8 payload for text frames.
 */
text: string | null, 
/**
 * Base64 payload for binary/ping/pong frames.
 */
base64: string | null, size: number, 
/**
 * Unix epoch milliseconds.
 */
timestamp: number, } | { "type": "closed", code: number | null, reason: string, byClient: boolean, } | { "type": "error", message: string, };
