// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplyMode } from "./ReplyMode";
import type { ReplyRule } from "./ReplyRule";

export type WsServerConfig = { mode?: ReplyMode, 
/**
 * Sent to each client right after it connects.
 */
greeting?: string, rules?: Array<ReplyRule>, };
